//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABT_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ABT_USERS()
        {
            this.ApplicationApprovers = new HashSet<ApplicationApprover>();
            this.ElectronicDegreeInformations = new HashSet<ElectronicDegreeInformation>();
            this.ElectronicDegreeInstitutions = new HashSet<ElectronicDegreeInstitution>();
            this.ElectronicDegreeInstMajors = new HashSet<ElectronicDegreeInstMajor>();
            this.ElectronicDegreeInstMajors1 = new HashSet<ElectronicDegreeInstMajor>();
            this.ElectronicDegreeInstSigners = new HashSet<ElectronicDegreeInstSigner>();
            this.ElectronicDegreeInstSigners1 = new HashSet<ElectronicDegreeInstSigner>();
            this.ElectronicDegreeMajors = new HashSet<ElectronicDegreeMajor>();
            this.ElectronicDegreeMappings = new HashSet<ElectronicDegreeMapping>();
            this.ElectronicDegreeMappings1 = new HashSet<ElectronicDegreeMapping>();
            this.ElectronicDegreeOperators = new HashSet<ElectronicDegreeOperator>();
            this.ElectronicDegreeOperators1 = new HashSet<ElectronicDegreeOperator>();
            this.ElectronicDegreeOperators2 = new HashSet<ElectronicDegreeOperator>();
            this.ElectronicDegreePermissions = new HashSet<ElectronicDegreePermission>();
            this.ElectronicDegreePermissions1 = new HashSet<ElectronicDegreePermission>();
            this.ElectronicDegreePermissions2 = new HashSet<ElectronicDegreePermission>();
            this.ElectronicDegreePermissions3 = new HashSet<ElectronicDegreePermission>();
            this.ElectronicDegreeRequests = new HashSet<ElectronicDegreeRequest>();
            this.ElectronicDegreeTransactions = new HashSet<ElectronicDegreeTransaction>();
            this.FiscalRecordIssuerDefaults = new HashSet<FiscalRecordIssuerDefault>();
            this.FiscalRecordTransactions = new HashSet<FiscalRecordTransaction>();
            this.InquiryApprovers = new HashSet<InquiryApprover>();
            this.LateFeeCharges = new HashSet<LateFeeCharge>();
            this.Signers = new HashSet<Signer>();
            this.Transactions = new HashSet<Transaction1>();
            this.TranscriptGradingHistories = new HashSet<TranscriptGradingHistory>();
        }
    
        public string OPERATOR_ID { get; set; }
        public string OPID_PASSWORD { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public Nullable<System.DateTime> LAST_LOGON_DATE { get; set; }
        public Nullable<System.DateTime> LAST_LOGON_TIME { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string LOGON_ID { get; set; }
        public string SEVIS_LOGON { get; set; }
        public string DOMAIN { get; set; }
        public string STATUS { get; set; }
    
        public virtual CODE_DOMAIN CODE_DOMAIN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationApprover> ApplicationApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInformation> ElectronicDegreeInformations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInstitution> ElectronicDegreeInstitutions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInstMajor> ElectronicDegreeInstMajors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInstMajor> ElectronicDegreeInstMajors1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInstSigner> ElectronicDegreeInstSigners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInstSigner> ElectronicDegreeInstSigners1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeMajor> ElectronicDegreeMajors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeMapping> ElectronicDegreeMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeMapping> ElectronicDegreeMappings1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeOperator> ElectronicDegreeOperators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeOperator> ElectronicDegreeOperators1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeOperator> ElectronicDegreeOperators2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreePermission> ElectronicDegreePermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreePermission> ElectronicDegreePermissions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreePermission> ElectronicDegreePermissions2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreePermission> ElectronicDegreePermissions3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeRequest> ElectronicDegreeRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeTransaction> ElectronicDegreeTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiscalRecordIssuerDefault> FiscalRecordIssuerDefaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiscalRecordTransaction> FiscalRecordTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryApprover> InquiryApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LateFeeCharge> LateFeeCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Signer> Signers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction1> Transactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranscriptGradingHistory> TranscriptGradingHistories { get; set; }
    }
}
