//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABT_WEBACTIONS
    {
        public string PEOPLE_ORG_CODE { get; set; }
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public string PEOPLE_ORG_ID { get; set; }
        public string ACTION_TYPE { get; set; }
        public System.DateTime ACTION_DATE { get; set; }
        public System.DateTime ACTION_TIME { get; set; }
        public int ACTION_STATUS { get; set; }
        public string GOVERNMENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string FORMER_NAME { get; set; }
        public string NAME_PREFIX { get; set; }
        public string NAME_SUFFIX { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string ADDRESS_LINE_3 { get; set; }
        public string ADDRESS_CITY { get; set; }
        public string ADDRESS_STATE { get; set; }
        public string ADDRESS_ZIPCODE { get; set; }
        public string ADDRESS_COUNTY { get; set; }
        public string ADDRESS_COUNTRY { get; set; }
        public string ADDRESS_DAY_PHONE { get; set; }
        public string ADDRESS_EVENING_PHONE { get; set; }
        public string VISA { get; set; }
        public string E_MAIL_ADDRESS { get; set; }
        public string PROGRAM { get; set; }
        public string DEGREE { get; set; }
        public string CURRICULUM { get; set; }
        public string REQUEST_YEAR { get; set; }
        public string REQUEST_TERM { get; set; }
        public string REQUEST_FULL_PART { get; set; }
        public string STATE_RESIDENCY { get; set; }
        public string REQUEST_HOUSING { get; set; }
        public string CURRENT_EDUCATION { get; set; }
        public string GENDER { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string PREVIOUS_ATTEND { get; set; }
        public string PREVIOUS_APPLY { get; set; }
        public string PREVIOUS_APPLY_YY { get; set; }
        public string PREVIOUS_COLLEGE_1 { get; set; }
        public string PREVIOUS_DEGREE_1 { get; set; }
        public string PREVIOUS_COLLEGE_2 { get; set; }
        public string PREVIOUS_DEGREE_2 { get; set; }
        public string PREVIOUS_COLLEGE_3 { get; set; }
        public string PREVIOUS_DEGREE_3 { get; set; }
        public string PREVIOUS_COLLEGE_4 { get; set; }
        public string PREVIOUS_DEGREE_4 { get; set; }
        public string PREVIOUS_COLLEGE_5 { get; set; }
        public string PREVIOUS_DEGREE_5 { get; set; }
        public string COMMENT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string RELIGION { get; set; }
        public string RETIRED { get; set; }
        public string PREFERRED_ADD { get; set; }
        public string PERMANENT_HOME { get; set; }
        public string RELEASE_INFO { get; set; }
        public string DUAL_CITIZENSHIP { get; set; }
        public string BIRTH_COUNTRY { get; set; }
        public string PRIMARY_LANGUAGE { get; set; }
        public string HOME_LANGUAGE { get; set; }
        public Nullable<int> MONTHS_IN_COUNTRY { get; set; }
        public string ETHNICITY { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string VETERAN { get; set; }
        public string CITIZENSHIP { get; set; }
        public string FIN_AID_CANDIDATE { get; set; }
        public string DEGREE_CANDIDATE { get; set; }
        public string EXTRA_CURRICULAR { get; set; }
        public string INTEREST { get; set; }
        public int WEB_ID { get; set; }
        public string TRANS_COLL_NAME { get; set; }
        public string TRANS_COLL_ADDR1 { get; set; }
        public string TRANS_COLL_ADDR2 { get; set; }
        public string TRANS_COLL_CITY { get; set; }
        public string TRANS_COLL_STATE { get; set; }
        public string TRANS_COLL_ZIP { get; set; }
        public string TRANS_DEGREE_DATES { get; set; }
        public string CURR_ATTEND { get; set; }
        public string LAST_ATT_TERM { get; set; }
        public string TRANS_INSTRUCTIONS { get; set; }
        public string LAST_ATT_YEAR { get; set; }
        public string NICKNAME { get; set; }
        public string PREVIOUS_APPLY_TERM { get; set; }
        public string OTHER_INTEREST { get; set; }
        public string OTHER_COUNTRY { get; set; }
        public string DISABILITY_1 { get; set; }
        public string DISABILITY_2 { get; set; }
        public string OTHER_DISABILITY { get; set; }
        public string SPECIAL_REQ_1 { get; set; }
        public string SPECIAL_REQ_2 { get; set; }
        public string OTHER_SPECIAL_REQ { get; set; }
        public string PREVIOUS_COLLEGE_TEXT_1 { get; set; }
        public string PREVIOUS_COLLEGE_TEXT_2 { get; set; }
        public string PREVIOUS_COLLEGE_TEXT_3 { get; set; }
        public string PREVIOUS_COLLEGE_TEXT_4 { get; set; }
        public string PREVIOUS_COLLEGE_TEXT_5 { get; set; }
        public string PREVIOUS_FICE_1 { get; set; }
        public string PREVIOUS_FICE_2 { get; set; }
        public string PREVIOUS_FICE_3 { get; set; }
        public string PREVIOUS_FICE_4 { get; set; }
        public string PREVIOUS_FICE_5 { get; set; }
        public string PREVIOUS_CURRICULUM_1 { get; set; }
        public string PREVIOUS_CURRICULUM_2 { get; set; }
        public string PREVIOUS_CURRICULUM_3 { get; set; }
        public string PREVIOUS_CURRICULUM_4 { get; set; }
        public string PREVIOUS_CURRICULUM_5 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_START_DATE_1 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_START_DATE_2 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_START_DATE_3 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_START_DATE_4 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_START_DATE_5 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_END_DATE_1 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_END_DATE_2 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_END_DATE_3 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_END_DATE_4 { get; set; }
        public Nullable<System.DateTime> PREVIOUS_END_DATE_5 { get; set; }
        public string REQUEST_SESSION { get; set; }
    }
}
