//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACADEMICCALENDAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACADEMICCALENDAR()
        {
            this.DegreeCosts = new HashSet<DegreeCost>();
        }
    
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string FISCAL_YEAR { get; set; }
        public Nullable<int> ACADEMIC_WEEKS { get; set; }
        public Nullable<int> ACADEMIC_MONTHS { get; set; }
        public Nullable<int> NUMBER_COURSES { get; set; }
        public Nullable<System.DateTime> PRE_REG_DATE { get; set; }
        public Nullable<System.DateTime> REG_DATE { get; set; }
        public Nullable<System.DateTime> LAST_REG_DATE { get; set; }
        public Nullable<System.DateTime> GRADE_WTHDRWL_DATE { get; set; }
        public Nullable<System.DateTime> GRADE_PENALTY_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string TRUE_ACADEMIC_YEAR { get; set; }
        public string FIN_AID_YEAR { get; set; }
        public string FIN_AID_TERM { get; set; }
        public Nullable<System.DateTime> MID_START_DATE { get; set; }
        public Nullable<System.DateTime> MID_END_DATE { get; set; }
        public Nullable<System.DateTime> FINAL_START_DATE { get; set; }
        public Nullable<System.DateTime> FINAL_END_DATE { get; set; }
        public int SessionPeriodId { get; set; }
        public bool FinAidNonTerm { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DegreeCost> DegreeCosts { get; set; }
    }
}
