//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIONTOSCHEDULE
    {
        public int RULE_ID { get; set; }
        public int SEQ_NUM { get; set; }
        public string ACTION_ID { get; set; }
        public int CONTINGENT_UPON { get; set; }
        public int OFFSET_DAYS { get; set; }
        public string ACTION_NAME { get; set; }
        public string RESP_STAFF { get; set; }
        public System.DateTime SCHED_TIME { get; set; }
        public string ALT_RECIPIENT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string DURATION { get; set; }
    }
}
