//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVITY
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ACTIVITY_TYPE { get; set; }
        public string ACTIVITY_CODE { get; set; }
        public string POSITION { get; set; }
        public decimal HOURS_PER_WEEK { get; set; }
        public int WEEKS_PER_YEAR { get; set; }
        public int NUMBER_OF_YEARS { get; set; }
        public string NINTH_GRADE { get; set; }
        public string TENTH_GRADE { get; set; }
        public string ELEVENTH_GRADE { get; set; }
        public string TWELFTH_GRADE { get; set; }
        public string POST_SECONDARY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
    }
}
