//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIONCRITERIA
    {
        public int RULE_ID { get; set; }
        public int SEQ_NUM { get; set; }
        public string LEFT_PAREN { get; set; }
        public string TABLE_NAME { get; set; }
        public string NEW_OLD { get; set; }
        public string COLUMN_NAME { get; set; }
        public string OPERATOR { get; set; }
        public string CRITERIA { get; set; }
        public string RIGHT_PAREN { get; set; }
        public string AND_OR { get; set; }
        public string CHECK_UPDATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
    }
}
