//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public string PEOPLE_ORG_CODE { get; set; }
        public string PEOPLE_ORG_ID { get; set; }
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string ADDRESS_LINE_3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string COUNTY { get; set; }
        public string DAY_PHONE { get; set; }
        public string EVENING_PHONE { get; set; }
        public string MAIN_FAX { get; set; }
        public string ALTERNATE_FAX { get; set; }
        public string NO_MAIL { get; set; }
        public string NO_CALL_DAY_PHONE { get; set; }
        public string NO_CALL_EVE_PHONE { get; set; }
        public string NOT_VALID_BEG_MM { get; set; }
        public string NOT_VALID_BEG_YY { get; set; }
        public string NOT_VALID_END_MM { get; set; }
        public string NOT_VALID_END_YY { get; set; }
        public string ALTERNATE_ADD_TYPE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string CITY_PREFIX { get; set; }
        public string CITY_SUFFIX { get; set; }
        public string EMAIL_ADDRESS { get; set; }
        public string ADDRESS_LINE_4 { get; set; }
        public string HOUSE_NUMBER { get; set; }
    }
}
