//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADJUSTMENTPOLICY
    {
        public int ADJUSTMENT_POLICY_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string POLICY_NAME { get; set; }
        public string POLICY_DESCRIPTION { get; set; }
        public string STATUS { get; set; }
        public string SCHEDULE_BASE { get; set; }
        public string SCHEDULE_BY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
