//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternateGradeResultDepartment
    {
        public int AltGradeResultId { get; set; }
        public string Department { get; set; }
        public string CreditType { get; set; }
        public decimal MaxQualityPoints { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
    
        public virtual AlternateGradeResult AlternateGradeResult { get; set; }
        public virtual CODE_ACACREDITTYPE CODE_ACACREDITTYPE { get; set; }
        public virtual CODE_DEPARTMENT CODE_DEPARTMENT { get; set; }
    }
}
