//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternateGradeResultDetail
    {
        public int AltGradeResultDetailId { get; set; }
        public int AltGradeResultId { get; set; }
        public byte SortOrder { get; set; }
        public string GradeValue { get; set; }
        public decimal QualityPoints { get; set; }
        public byte NumberOfStudents { get; set; }
        public decimal PercentageOfStudents { get; set; }
        public bool IsFailingGrade { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
    
        public virtual AlternateGradeResult AlternateGradeResult { get; set; }
    }
}
