//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlternateGradeResult
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AlternateGradeResult()
        {
            this.AlternateGradeResultDetails = new HashSet<AlternateGradeResultDetail>();
        }
    
        public int AltGradeResultId { get; set; }
        public int AltGradeHeaderSettingId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
    
        public virtual AlternateGradeHeaderSetting AlternateGradeHeaderSetting { get; set; }
        public virtual AlternateGradeResultCollege AlternateGradeResultCollege { get; set; }
        public virtual AlternateGradeResultCurriculum AlternateGradeResultCurriculum { get; set; }
        public virtual AlternateGradeResultDepartment AlternateGradeResultDepartment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternateGradeResultDetail> AlternateGradeResultDetails { get; set; }
        public virtual AlternateGradeResultEvent AlternateGradeResultEvent { get; set; }
        public virtual AlternateGradeResultProgram AlternateGradeResultProgram { get; set; }
    }
}
