//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALUMNIDEGREE
    {
        public string PEOPLE_CODE_ID { get; set; }
        public string CLASS_YEAR { get; set; }
        public string PROGRAM { get; set; }
        public string DEGREE { get; set; }
        public string CURRICULUM { get; set; }
        public string COLLEGE { get; set; }
        public string DEPARTMENT { get; set; }
        public string NONTRAD_PROGRAM { get; set; }
        public string TRANSCRIPT_SEQ { get; set; }
        public string COMMENTS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string POPULATION { get; set; }
        public Nullable<System.DateTime> GRADUATION_DATE { get; set; }
    }
}
