//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationTestScore
    {
        public int ApplicationTestScoreId { get; set; }
        public int ApplicationId { get; set; }
        public int Test { get; set; }
        public Nullable<int> TestType { get; set; }
        public System.DateTime TestDate { get; set; }
        public decimal NumericScore { get; set; }
        public string AlphaScore { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public string Level { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
