//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserDefined
    {
        public int ApplicationUserDefinedId { get; set; }
        public int ApplicationId { get; set; }
        public string ColumnName { get; set; }
        public string ColumnValue { get; set; }
        public byte ColumnType { get; set; }
        public string ColumnLabel { get; set; }
        public bool IsUploading { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
