//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationAttachment
    {
        public int ApplicationAttachmentId { get; set; }
        public int ApplicationId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string FileTitle { get; set; }
        public int FileType { get; set; }
        public string FileExtension { get; set; }
        public byte[] FileContent { get; set; }
        public string FileName { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
