//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationEducation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationEducation()
        {
            this.ApplicationEducationEnrollments = new HashSet<ApplicationEducationEnrollment>();
        }
    
        public int ApplicationEducationId { get; set; }
        public int ApplicationId { get; set; }
        public string InstitutionName { get; set; }
        public string City { get; set; }
        public Nullable<int> StateProvinceId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string FiceCode { get; set; }
        public string EtsCode { get; set; }
        public string NumberOfCredits { get; set; }
        public string GPA { get; set; }
        public string OtherInstitutionName { get; set; }
        public string CLASS_GRADE { get; set; }
        public string OtherInstitution { get; set; }
        public Nullable<bool> isTransfer { get; set; }
        public string TotalScoreMarks { get; set; }
        public Nullable<decimal> TotalScorePercent { get; set; }
        public string SeatNumber { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationEducationEnrollment> ApplicationEducationEnrollments { get; set; }
    }
}
