//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationSource
    {
        public int ApplicationSourceId { get; set; }
        public int ApplicationId { get; set; }
        public Nullable<int> SourceId { get; set; }
    
        public virtual Application Application { get; set; }
    }
}
