//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASSESSMENTRULE
    {
        public string ASSESSMENT_RULE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string PREBILL_FLAG { get; set; }
        public string TRAD_NONTRAD { get; set; }
        public string SELECT_CRITERIA { get; set; }
        public string STORED_PROC_NAME { get; set; }
        public string LONG_DESC { get; set; }
        public string HELP_DESC { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string SECTION_FEE_FLAG { get; set; }
        public string STORED_PROC_IND { get; set; }
        public string EVENT_ID { get; set; }
        public string EVENT_SUB_TYPE { get; set; }
        public string SECTION { get; set; }
        public string CUSTOM_SQL { get; set; }
        public string RULE_TYPE { get; set; }
        public string COURSE_SESSION { get; set; }
    }
}
