//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentTemplateTypeRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignmentTemplateTypeRule()
        {
            this.AssignmentTemplateDetails = new HashSet<AssignmentTemplateDetail>();
        }
    
        public int AssignmentTemplateTypeRuleId { get; set; }
        public int AssignmentTemplateHeaderId { get; set; }
        public int AssignmentTypeId { get; set; }
        public int MidtermDropLowest { get; set; }
        public int MidtermDropHighest { get; set; }
        public decimal MidtermWeight { get; set; }
        public int FinalDropLowest { get; set; }
        public int FinalDropHighest { get; set; }
        public decimal FinalWeight { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentTemplateDetail> AssignmentTemplateDetails { get; set; }
        public virtual AssignmentTemplateHeader AssignmentTemplateHeader { get; set; }
    }
}
