//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentTemplateHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignmentTemplateHeader()
        {
            this.AssignmentTemplateSections = new HashSet<AssignmentTemplateSection>();
            this.AssignmentTemplateShares = new HashSet<AssignmentTemplateShare>();
            this.AssignmentTemplateTypeRules = new HashSet<AssignmentTemplateTypeRule>();
        }
    
        public int AssignmentTemplateHeaderId { get; set; }
        public int SessionPeriodId { get; set; }
        public string Name { get; set; }
        public byte AssignmentWeightingMethod { get; set; }
        public bool UseWeightedAssignmentTypes { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public int CreatedBy { get; set; }
        public bool IsRestrictive { get; set; }
        public Nullable<bool> IsDateByAssignmentType { get; set; }
        public bool DefaultGradeMapping { get; set; }
        public bool AutomaticOverallGrades { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentTemplateSection> AssignmentTemplateSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentTemplateShare> AssignmentTemplateShares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignmentTemplateTypeRule> AssignmentTemplateTypeRules { get; set; }
    }
}
