//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentTypeRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssignmentTypeRule()
        {
            this.SECTIONGRADINGSUMMARies = new HashSet<SECTIONGRADINGSUMMARY>();
        }
    
        public int AssignmentTypeRuleId { get; set; }
        public int SectionId { get; set; }
        public int AssignmentTypeId { get; set; }
        public int MidtermDropLowest { get; set; }
        public int MidtermDropHighest { get; set; }
        public decimal MidtermWeight { get; set; }
        public int FinalDropLowest { get; set; }
        public int FinalDropHighest { get; set; }
        public decimal FinalWeight { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreateOpid { get; set; }
        public string CreateTerminal { get; set; }
        public System.DateTime RevisionDateTime { get; set; }
        public string RevisionOpid { get; set; }
        public string RevisionTerminal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SECTIONGRADINGSUMMARY> SECTIONGRADINGSUMMARies { get; set; }
    }
}
