//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BATCHHEADER
    {
        public string TABLENAME { get; set; }
        public string BATCH_TYPE { get; set; }
        public string BATCH_NUMBER { get; set; }
        public System.DateTime BATCH_DATE { get; set; }
        public int BATCH_SEQUENCE { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public decimal AMOUNT_TOTAL { get; set; }
        public int ITEM_TOTAL { get; set; }
        public decimal AMOUNT_ENTERED { get; set; }
        public int ITEMS_ENTERED { get; set; }
        public string OFFICE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public Nullable<int> NEXT_KEY { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string DELETED_FLAG { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public string DELETE_OPID { get; set; }
        public string CR_PAYMENT_TYPE { get; set; }
        public string CR_CASH_CODE { get; set; }
    }
}
