//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BETA_BULK_IDS
    {
        public int RECORD_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string LOGIN_ID { get; set; }
        public string PASSWORD { get; set; }
        public string OVERRIDE_EXISTING { get; set; }
        public string ACCOUNT_EMAIL { get; set; }
        public string ACCOUNT_ID { get; set; }
        public string SUCCESS { get; set; }
        public string ERROR_MSG { get; set; }
        public Nullable<System.DateTime> CREATE_DATETIME { get; set; }
    }
}
