//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockRegRuleGroupBlock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlockRegRuleGroupBlock()
        {
            this.BlockRegisteredPeoples = new HashSet<BlockRegisteredPeople>();
        }
    
        public int BlockRegRuleGroupBlockId { get; set; }
        public int BlockRegistrationRuleGroupId { get; set; }
        public int BlockRegistrationGroupId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public int EnteredBy { get; set; }
        public int ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockRegisteredPeople> BlockRegisteredPeoples { get; set; }
        public virtual BlockRegistrationGroup BlockRegistrationGroup { get; set; }
        public virtual BlockRegistrationRuleGroup BlockRegistrationRuleGroup { get; set; }
    }
}
