//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockWebRegRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlockWebRegRule()
        {
            this.BlockWebRegRuleGroups = new HashSet<BlockWebRegRuleGroup>();
        }
    
        public int BlockWebRegRuleId { get; set; }
        public string RuleName { get; set; }
        public int SessionPeriodId { get; set; }
        public int Priority { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ProgramOfStudyId { get; set; }
        public Nullable<int> CollegeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> ClassLevelId { get; set; }
        public Nullable<int> PopulationId { get; set; }
        public Nullable<int> FullTimePartTimeId { get; set; }
        public Nullable<int> NonTraditionalProgramId { get; set; }
        public Nullable<int> AcademicRateId { get; set; }
        public Nullable<int> CollegeAttendId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string RuleViewName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockWebRegRuleGroup> BlockWebRegRuleGroups { get; set; }
    }
}
