//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockRegistrationRule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BlockRegistrationRule()
        {
            this.BlockRegistrationRuleGroups = new HashSet<BlockRegistrationRuleGroup>();
        }
    
        public int BlockRegistrationRuleId { get; set; }
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public int TermPeriodId { get; set; }
        public int Priority { get; set; }
        public bool IsBlockRegistrationOnly { get; set; }
        public string ViewName { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public int EnteredBy { get; set; }
        public int ModifiedBy { get; set; }
    
        public virtual TermPeriod TermPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlockRegistrationRuleGroup> BlockRegistrationRuleGroups { get; set; }
    }
}
