//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockRegisteredPeople
    {
        public int BlockRegisteredPeopleId { get; set; }
        public int PersonId { get; set; }
        public int BlockRegRuleGroupBlockId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual BlockRegRuleGroupBlock BlockRegRuleGroupBlock { get; set; }
    }
}
