//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CASHRECEIPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CASHRECEIPT()
        {
            this.CashReceiptXmls = new HashSet<CashReceiptXml>();
            this.FiscalRecordTransactions = new HashSet<FiscalRecordTransaction>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public int RECEIPT_NUMBER { get; set; }
        public string PEOPLE_ORG_CODE { get; set; }
        public string PEOPLE_ORG_ID { get; set; }
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string BATCH { get; set; }
        public System.DateTime ENTRY_DATE { get; set; }
        public string OFFICE { get; set; }
        public string RECEIPT_PAYMENT_TYPE { get; set; }
        public string CASH_RECEIPT_CODE { get; set; }
        public decimal RECEIPT_AMOUNT { get; set; }
        public string PEOPLE_ORIGIN_ID { get; set; }
        public string PEOPLE_ORIGIN_NAME { get; set; }
        public string ORG_ORIGIN_ID { get; set; }
        public string ORG_ORIGIN_NAME { get; set; }
        public string CASH_RECEIPT_FOR { get; set; }
        public string CASH_RECEIPT_NOTE { get; set; }
        public string RECEIPT_PRINTED { get; set; }
        public Nullable<System.DateTime> RECEIPT_PRINT_DATE { get; set; }
        public string PROJECT_ID { get; set; }
        public Nullable<int> CHECK_NUMBER { get; set; }
        public Nullable<System.DateTime> CHECK_DATE { get; set; }
        public string CHECK_ACCOUNT { get; set; }
        public string VOID_FLAG { get; set; }
        public Nullable<System.DateTime> VOID_DATE { get; set; }
        public string POSTED_FLAG { get; set; }
        public Nullable<System.DateTime> POSTED_DATE { get; set; }
        public string REVERSED { get; set; }
        public Nullable<int> REVERSED_NUMBER { get; set; }
        public decimal UNDISTRIBUTED_AMT { get; set; }
        public string FIN_AID_REDUCED { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string CASH_RECEIPT_DESC { get; set; }
        public string PAY_PLAN_APPLIED { get; set; }
        public string VOID_OPID { get; set; }
        public string REVERSAL_OPID { get; set; }
        public Nullable<int> PaymentTransactionId { get; set; }
    
        public virtual PaymentTransaction PaymentTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashReceiptXml> CashReceiptXmls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiscalRecordTransaction> FiscalRecordTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
