//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashReceiptXml
    {
        public int CashReceiptXmlId { get; set; }
        public int ReceiptNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ReceiptXml { get; set; }
        public string HtmlContent { get; set; }
    
        public virtual CASHRECEIPT CASHRECEIPT { get; set; }
    }
}
