//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARTOFACCOUNT
    {
        public string GL_ACCOUNT { get; set; }
        public string NAME { get; set; }
        public System.DateTime START_DATE { get; set; }
        public System.DateTime END_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string AR_FLAG { get; set; }
        public string CASH_FLAG { get; set; }
        public string ACTALIAS { get; set; }
        public string PSTNGTYP { get; set; }
        public string TPCLBLNC { get; set; }
        public string ACTIVE { get; set; }
        public Nullable<int> ACTINDX { get; set; }
    }
}
