//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHARGECREDIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHARGECREDIT()
        {
            this.ChargeCreditApplications = new HashSet<ChargeCreditApplication>();
            this.ChargeCreditApplications1 = new HashSet<ChargeCreditApplication>();
            this.ChargeCreditDueDateHistories = new HashSet<ChargeCreditDueDateHistory>();
            this.ChargeCreditScholarships = new HashSet<ChargeCreditScholarship>();
            this.ChargeCreditScholarshipDetails = new HashSet<ChargeCreditScholarshipDetail>();
            this.ChargeCreditTaxes = new HashSet<ChargeCreditTax>();
            this.ChargeCreditTaxes1 = new HashSet<ChargeCreditTax>();
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
            this.InvoiceDetails1 = new HashSet<InvoiceDetail>();
            this.LateFeeCharges = new HashSet<LateFeeCharge>();
            this.LateFeeCharges1 = new HashSet<LateFeeCharge>();
            this.PFIChargeCredits = new HashSet<PFIChargeCredit>();
            this.Reported1098TSummaryDetail = new HashSet<Reported1098TSummaryDetail>();
        }
    
        public int CHARGECREDITNUMBER { get; set; }
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public string PEOPLE_ORG_CODE { get; set; }
        public string PEOPLE_ORG_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string CHARGE_CREDIT_CODE { get; set; }
        public string CHARGE_CREDIT_TYPE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<decimal> PAID_AMOUNT { get; set; }
        public Nullable<decimal> BALANCE_AMOUNT { get; set; }
        public string NOTE { get; set; }
        public string PREBILL_FLAG { get; set; }
        public string TAXABLE { get; set; }
        public string FIN_AID_ELIGIBLE { get; set; }
        public string REFUND_ELIGIBLE { get; set; }
        public string BATCH { get; set; }
        public string PRINTED_ON_STMT { get; set; }
        public Nullable<System.DateTime> FIRST_STMT_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public string CRG_CRD_DESC { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public string JOURNAL_SOURCE { get; set; }
        public string JOURNAL_ENTRY { get; set; }
        public string ANTICIPATED_FLAG { get; set; }
        public Nullable<System.DateTime> SCHED_DISB_DATE { get; set; }
        public string ASSESSED_FLAG { get; set; }
        public string VOID_FLAG { get; set; }
        public string POSTED_FLAG { get; set; }
        public Nullable<System.DateTime> POSTED_DATE { get; set; }
        public string FISCAL_YEAR { get; set; }
        public string FISCAL_PERIOD { get; set; }
        public string PROJECT_ID { get; set; }
        public string STATEMENT_TYPE { get; set; }
        public string SUMMARY_TYPE { get; set; }
        public Nullable<int> RECEIPT_NUMBER { get; set; }
        public string DETAIL_FLAG { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public Nullable<System.DateTime> REVISION_DATE { get; set; }
        public Nullable<System.DateTime> REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string TRUE_ACADEMIC_YEAR { get; set; }
        public string BEGINNING_BAL_FLAG { get; set; }
        public Nullable<System.DateTime> VOID_DATE { get; set; }
        public string REVERSED { get; set; }
        public Nullable<int> REVERSED_NUMBER { get; set; }
        public string PAYPLAN_FLAG { get; set; }
        public string REFUND_EXPORT { get; set; }
        public Nullable<System.DateTime> REFUND_EXPORT_DATE { get; set; }
        public string REFUND_EXPORT_OPID { get; set; }
        public Nullable<int> REFUND_CHECK_NUM { get; set; }
        public Nullable<System.DateTime> REFUND_CHECK_DATE { get; set; }
        public string SPONSOR_ID { get; set; }
        public string SPONSORED_ID { get; set; }
        public Nullable<int> AGREEMENT_NUMBER { get; set; }
        public string PAYMENT_OPTION { get; set; }
        public string PAYPLAN_ELIGIBLE { get; set; }
        public string TYPE_1098 { get; set; }
        public Nullable<decimal> RATE_AMOUNT { get; set; }
        public string PER_CREDIT_FLAT { get; set; }
        public string ASSESSMENT_RULE_ID { get; set; }
        public string ASSESSMENT_RULE_TYPE { get; set; }
        public bool IsATax { get; set; }
        public bool IsTitleIV { get; set; }
        public bool IsPrivateLoan { get; set; }
        public bool IsInstitutionalDebt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeCreditApplication> ChargeCreditApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeCreditApplication> ChargeCreditApplications1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeCreditDueDateHistory> ChargeCreditDueDateHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeCreditScholarship> ChargeCreditScholarships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeCreditScholarshipDetail> ChargeCreditScholarshipDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeCreditTax> ChargeCreditTaxes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeCreditTax> ChargeCreditTaxes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LateFeeCharge> LateFeeCharges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LateFeeCharge> LateFeeCharges1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PFIChargeCredit> PFIChargeCredits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reported1098TSummaryDetail> Reported1098TSummaryDetail { get; set; }
    }
}
