//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChargeCreditDueDateHistory
    {
        public int ChargeCreditDueDateHistoryId { get; set; }
        public int ChargeCreditNumber { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
    
        public virtual CHARGECREDIT CHARGECREDIT { get; set; }
    }
}
