//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_ACACREDITTYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CODE_ACACREDITTYPE()
        {
            this.AlternateGradeResultColleges = new HashSet<AlternateGradeResultCollege>();
            this.AlternateGradeResultCurriculums = new HashSet<AlternateGradeResultCurriculum>();
            this.AlternateGradeResultDepartments = new HashSet<AlternateGradeResultDepartment>();
            this.AlternateGradeResultPrograms = new HashSet<AlternateGradeResultProgram>();
        }
    
        public string CODE_VALUE_KEY { get; set; }
        public string CODE_VALUE { get; set; }
        public string SHORT_DESC { get; set; }
        public string MEDIUM_DESC { get; set; }
        public string LONG_DESC { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string CRD_GRADE_SAME { get; set; }
        public decimal CRD_LOW_GRADE { get; set; }
        public decimal CRD_HIGH_GRADE { get; set; }
        public string CRD_BILLING_SAME { get; set; }
        public decimal CRD_LOW_BILLING { get; set; }
        public decimal CRD_HIGH_BILLING { get; set; }
        public string CRD_FTE_SAME { get; set; }
        public decimal CRD_LOW_FTE { get; set; }
        public decimal CRD_HIGH_FTE { get; set; }
        public string CRD_WORKLOAD_SAME { get; set; }
        public decimal CRD_LOW_WORKLOAD { get; set; }
        public decimal CRD_HIGH_WORKLOAD { get; set; }
        public string CRD_FED_FA_SAME { get; set; }
        public decimal CRD_LOW_FED_FA { get; set; }
        public decimal CRD_HIGH_FED_FA { get; set; }
        public string CRD_ST_FA_SAME { get; set; }
        public decimal CRD_LOW_ST_FA { get; set; }
        public decimal CRD_HIGH_ST_FA { get; set; }
        public string CRD_CNTY_FA_SAME { get; set; }
        public decimal CRD_LOW_CNTY_FA { get; set; }
        public decimal CRD_HIGH_CNTY_FA { get; set; }
        public string CRD_FED_RPT_SAME { get; set; }
        public decimal CRD_LOW_FED_RPT { get; set; }
        public decimal CRD_HIGH_FED_RPT { get; set; }
        public string CRD_ST_RPT_SAME { get; set; }
        public decimal CRD_LOW_ST_RPT { get; set; }
        public decimal CRD_HIGH_ST_RPT { get; set; }
        public string CRD_CNTY_RPT_SAME { get; set; }
        public decimal CRD_LOW_CNTY_RPT { get; set; }
        public decimal CRD_HIGH_CNTY_RPT { get; set; }
        public string CODE_XVAL { get; set; }
        public string CODE_XDESC { get; set; }
        public string ABT_JOIN { get; set; }
        public int CreditTypeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternateGradeResultCollege> AlternateGradeResultColleges { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternateGradeResultCurriculum> AlternateGradeResultCurriculums { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternateGradeResultDepartment> AlternateGradeResultDepartments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternateGradeResultProgram> AlternateGradeResultPrograms { get; set; }
    }
}
