//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_PERSONPHONETYPE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CODE_PERSONPHONETYPE()
        {
            this.ApplicationPhones = new HashSet<ApplicationPhone>();
            this.ApplicationPhoneTypeSettings = new HashSet<ApplicationPhoneTypeSetting>();
            this.InquiryPhoneTypeSettings = new HashSet<InquiryPhoneTypeSetting>();
            this.InquiryPhones = new HashSet<InquiryPhone>();
            this.PersonPhones = new HashSet<PersonPhone>();
            this.PersonPhoneHistories = new HashSet<PersonPhoneHistory>();
        }
    
        public string CODE_VALUE_KEY { get; set; }
        public string CODE_VALUE { get; set; }
        public string SHORT_DESC { get; set; }
        public string MEDIUM_DESC { get; set; }
        public string LONG_DESC { get; set; }
        public string DEFAULT_DESC { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationPhone> ApplicationPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationPhoneTypeSetting> ApplicationPhoneTypeSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryPhoneTypeSetting> InquiryPhoneTypeSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryPhone> InquiryPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonPhone> PersonPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonPhoneHistory> PersonPhoneHistories { get; set; }
    }
}
