//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_PAYMENTPLAN
    {
        public string CODE_VALUE_KEY { get; set; }
        public string CODE_VALUE { get; set; }
        public string SHORT_DESC { get; set; }
        public string MEDIUM_DESC { get; set; }
        public string LONG_DESC { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string CODE_XVAL { get; set; }
        public string CODE_XDESC { get; set; }
        public string ABT_JOIN { get; set; }
        public int NUM_OF_INSTALL { get; set; }
        public string HNDL_FEE_CODE { get; set; }
        public string OFFSET_CR_CODE { get; set; }
        public string INSTALL_CHG_CODE { get; set; }
        public string LATE_CHG_CODE { get; set; }
        public int DAY_PAYMENTS_DUE { get; set; }
        public string FIRST_DUE_TODAY { get; set; }
        public decimal MIN_FIRST_INST_AMT { get; set; }
        public decimal MIN_FIRST_INST_PER { get; set; }
    }
}
