//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_PLEDGETERM
    {
        public string CODE_VALUE_KEY { get; set; }
        public string CODE_VALUE { get; set; }
        public string SHORT_DESC { get; set; }
        public string MEDIUM_DESC { get; set; }
        public string LONG_DESC { get; set; }
        public string STATUS { get; set; }
        public string CODE_XVAL { get; set; }
        public string CODE_XDESC { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public int NUMBER_PAYMENTS { get; set; }
        public int NUMBER_MONTHS { get; set; }
        public string REMINDER_FLAG { get; set; }
        public string JANUARY { get; set; }
        public string FEBRUARY { get; set; }
        public string MARCH { get; set; }
        public string APRIL { get; set; }
        public string MAY { get; set; }
        public string JUNE { get; set; }
        public string JULY { get; set; }
        public string AUGUST { get; set; }
        public string SEPTEMBER { get; set; }
        public string OCTOBER { get; set; }
        public string NOVEMBER { get; set; }
        public string DECEMBER { get; set; }
    }
}
