//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_GIFTFORM
    {
        public string CODE_VALUE_KEY { get; set; }
        public string CODE_VALUE { get; set; }
        public string SHORT_DESC { get; set; }
        public string MEDIUM_DESC { get; set; }
        public string LONG_DESC { get; set; }
        public string STATUS { get; set; }
        public string CODE_XVAL { get; set; }
        public string CODE_XDESC { get; set; }
        public string CATEGORY { get; set; }
        public string GL_DEBIT { get; set; }
        public string GL_CREDIT { get; set; }
        public decimal CREDIT_PERCENTAGE { get; set; }
        public decimal MATCH_DONOR_PERCENT { get; set; }
        public string INCLUDE_SPOUSE { get; set; }
        public string INC_DECEASED_SPOUSE { get; set; }
        public string INC_SEPARATED_SPOUSE { get; set; }
        public decimal DONOR_PERCENTAGE { get; set; }
        public decimal SPOUSE_PERCENTAGE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
    }
}
