//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_COUNTRY_BK
    {
        public string CODE_VALUE_KEY { get; set; }
        public string CODE_VALUE { get; set; }
        public string SHORT_DESC { get; set; }
        public string MEDIUM_DESC { get; set; }
        public string LONG_DESC { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string PHONE_FORMAT { get; set; }
        public string CODE_XVAL { get; set; }
        public string CODE_XDESC { get; set; }
        public string ABT_JOIN { get; set; }
        public string PRINT_ON { get; set; }
        public string SEVIS_CODE { get; set; }
        public string ISO3166_CODE { get; set; }
        public string BIRTH_COUNTRY { get; set; }
        public string CITIZEN_COUNTRY { get; set; }
        public int CountryId { get; set; }
    }
}
