//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CODE_DOMAIN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CODE_DOMAIN()
        {
            this.ABT_USERS = new HashSet<ABT_USERS>();
        }
    
        public string CODE_VALUE_KEY { get; set; }
        public string CODE_VALUE { get; set; }
        public string SHORT_DESC { get; set; }
        public string MEDIUM_DESC { get; set; }
        public string LONG_DESC { get; set; }
        public string STATUS { get; set; }
        public string FULL_DOMAIN_NAME { get; set; }
        public bool IS_PRIMARY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ABT_USERS> ABT_USERS { get; set; }
    }
}
