//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMBINEMAILING
    {
        public string PEOPLE_CODE_ID { get; set; }
        public string COMBINE_MAILING { get; set; }
        public string COMBINE_CODE_ID { get; set; }
        public string COMBINE_NAMES { get; set; }
        public string FIRST_ID { get; set; }
        public string SECOND_ID { get; set; }
        public string ADDRESS_NAME_1 { get; set; }
        public string ADDRESS_NAME_2 { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
