//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPARISONRESULT
    {
        public int RUN_ID { get; set; }
        public decimal PROBABILITY { get; set; }
        public decimal COMPARATOR { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string PEOPLE_CODE_ID2 { get; set; }
        public decimal ADDR_COMPARATOR { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string ADDRESS_TYPE2 { get; set; }
        public string RESOLUTION { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
