//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConvPeopleOrgPhoneHierarchy
    {
        public int PhoneHierarchyId { get; set; }
        public string RecordType { get; set; }
        public string AddressType { get; set; }
        public byte PhoneField { get; set; }
        public byte Rank { get; set; }
        public bool IsPeopleHierarchy { get; set; }
    }
}
