//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class COUNSELOREXCEPTION
    {
        public int EXCEPTIONID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string COUNSELOR_CODE_ID { get; set; }
        public string PROGRAM { get; set; }
        public string DEGREE { get; set; }
        public string CURRICULUM { get; set; }
        public string COLLEGE { get; set; }
        public string DEPARTMENT { get; set; }
        public string CLASS_LEVEL { get; set; }
        public string POPULATION { get; set; }
        public string FULL_PART { get; set; }
        public string NONTRAD_PROGRAM { get; set; }
        public string COLLEGE_ATTEND { get; set; }
        public string ACADEMIC_RATING { get; set; }
        public int RATING { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
