//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATACHANx
    {
        public string PEOPLE_ORG_CODE { get; set; }
        public string PEOPLE_ORG_ID { get; set; }
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public System.DateTime CHANGE_DATE { get; set; }
        public System.DateTime CHANGE_TIME { get; set; }
        public string PREVIOUS_VALUE { get; set; }
        public string NEW_VALUE { get; set; }
        public string CHANGE_OPID { get; set; }
        public string CHANGE_TERMINAL { get; set; }
        public string ACKNOWLEDGED { get; set; }
        public Nullable<System.DateTime> ACKNOWLEDGED_DATE { get; set; }
        public string ACKNOWLEDGED_OPID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
    }
}
