//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEDICATION
    {
        public string PEOPLE_CODE_ID { get; set; }
        public string DEDICATION_VALUE { get; set; }
        public string DEDICATION_TYPE { get; set; }
        public string DEDICATION_NAME { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public Nullable<decimal> GOAL_AMOUNT { get; set; }
        public Nullable<decimal> ACHIEVED_AMOUNT { get; set; }
        public Nullable<decimal> EXPENSES_AMOUNT { get; set; }
        public string PROJECT_ID { get; set; }
        public string COMMENTS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
