//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DegreeCost
    {
        public int DegreeCostId { get; set; }
        public string AcademicYear { get; set; }
        public string AcademicTerm { get; set; }
        public string AcademicSession { get; set; }
        public string Program { get; set; }
        public string Degree { get; set; }
        public string Curriculum { get; set; }
        public Nullable<decimal> TuitionFeeAmount { get; set; }
        public Nullable<decimal> SuppliesAmount { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        public virtual ACADEMICCALENDAR ACADEMICCALENDAR { get; set; }
        public virtual CODE_CURRICULUM CODE_CURRICULUM { get; set; }
        public virtual CODE_DEGREE CODE_DEGREE { get; set; }
        public virtual CODE_PROGRAM CODE_PROGRAM { get; set; }
    }
}
