//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DegreeMappingNsc
    {
        public string AcademicYear { get; set; }
        public string AcademicTerm { get; set; }
        public string AcademicSession { get; set; }
        public string Program { get; set; }
        public string Degree { get; set; }
        public string Curriculum { get; set; }
        public string CipCode { get; set; }
        public short CipYear { get; set; }
        public string ProgramCredentialLevel { get; set; }
        public Nullable<decimal> PublishedProgramLength { get; set; }
        public string ProgramLengthMeasurement { get; set; }
        public string SpecialProgramIndicator { get; set; }
        public Nullable<decimal> WeeksInTitleIVAcademicYear { get; set; }
        public Nullable<System.DateTime> DefaultProgramBeginDate { get; set; }
        public bool IsGainfulEmployment { get; set; }
    
        public virtual CODE_PROGRAMCREDENTIALLEVEL CODE_PROGRAMCREDENTIALLEVEL { get; set; }
        public virtual CODE_SPECIALPROGRAMINDICATOR CODE_SPECIALPROGRAMINDICATOR { get; set; }
        public virtual DEGREEMAPPING DEGREEMAPPING { get; set; }
    }
}
