//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedPersonType
    {
        public int DeletedPersonTypeId { get; set; }
        public int PersonId { get; set; }
        public int PersonTypeId { get; set; }
        public Nullable<System.DateTime> FirstReadDate { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual PersonUser PersonUser { get; set; }
    }
}
