//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeletedChargeCredit
    {
        public int DeletedChargeCreditId { get; set; }
        public int ChargeCreditNumber { get; set; }
        public string PeopleOrgCodeId { get; set; }
        public string AcademicYear { get; set; }
        public string AcademicTerm { get; set; }
        public string AcademicSession { get; set; }
        public string ChargeCreditCode { get; set; }
        public string ChargeCreditType { get; set; }
        public decimal Amount { get; set; }
        public string Batch { get; set; }
        public string ChargeCreditDesc { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string AnticipatedFlag { get; set; }
        public string VoidFlag { get; set; }
        public Nullable<int> ReceiptNumber { get; set; }
        public Nullable<int> AgreementNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string CreateOpid { get; set; }
        public string DeleteOpid { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    }
}
