//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemographicForm
    {
        public int DemographicFormId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<int> Ethnicity { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> VeteranStatus { get; set; }
        public Nullable<bool> IsRetired { get; set; }
        public Nullable<int> PrimaryCitizenship { get; set; }
        public Nullable<int> SecondaryCitizenship { get; set; }
        public Nullable<int> Visa { get; set; }
        public Nullable<int> CountryOfBirth { get; set; }
        public Nullable<int> PrimaryLanguage { get; set; }
        public Nullable<int> SecondaryLanguage { get; set; }
        public Nullable<int> MonthsInCountry { get; set; }
    }
}
