//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEMOGRAPHIC
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string ETHNICITY { get; set; }
        public string GENDER { get; set; }
        public string MARITAL_STATUS { get; set; }
        public string RELIGION { get; set; }
        public string VETERAN { get; set; }
        public string CITIZENSHIP { get; set; }
        public string VISA { get; set; }
        public string RETIRED { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string LAST_ACTIVITY { get; set; }
        public string CURRENT_ACTIVITY { get; set; }
        public string PRIMARY_LANGUAGE { get; set; }
        public string HOME_LANGUAGE { get; set; }
        public Nullable<int> MONTHS_IN_COUNTRY { get; set; }
        public string DUAL_CITIZENSHIP { get; set; }
        public string PERMANENT_HOME { get; set; }
        public string LEGAL_RESIDENCE { get; set; }
        public string OtherLanguage { get; set; }
    }
}
