//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DISCOUNT
    {
        public int DISCOUNT_KEY { get; set; }
        public string DISCOUNT_CODE { get; set; }
        public string DISCOUNT_TYPE { get; set; }
        public string PERCT_FLAT { get; set; }
        public decimal AMOUNT { get; set; }
        public decimal PERCENTAGE { get; set; }
        public string CHARGECREDIT_CODE { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string STATUS { get; set; }
        public string VALID_ON_WEB { get; set; }
        public string SOURCE_ID { get; set; }
        public string AFFILIATION { get; set; }
        public string COMMENT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
