//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonorMessage
    {
        public int MessageId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Type { get; set; }
        public string Message { get; set; }
    
        public virtual MessageType MessageType { get; set; }
    }
}
