//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicDegreeInstSigner
    {
        public int ElectronicDegreeInstSignerId { get; set; }
        public int ElectronicDegreeInstitutionId { get; set; }
        public int SignerId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public string RevisionUserName { get; set; }
    
        public virtual ABT_USERS ABT_USERS { get; set; }
        public virtual ABT_USERS ABT_USERS1 { get; set; }
        public virtual ElectronicDegreeInstitution ElectronicDegreeInstitution { get; set; }
        public virtual Signer Signer { get; set; }
    }
}
