//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicDegreeInstitution
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectronicDegreeInstitution()
        {
            this.ElectronicDegreeInstMajors = new HashSet<ElectronicDegreeInstMajor>();
            this.ElectronicDegreeInstSigners = new HashSet<ElectronicDegreeInstSigner>();
            this.ElectronicDegreeOperators = new HashSet<ElectronicDegreeOperator>();
        }
    
        public int ElectronicDegreeInstitutionId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Folio { get; set; }
        public string FolioFormat { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public string RevisionUserName { get; set; }
    
        public virtual ABT_USERS ABT_USERS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInstMajor> ElectronicDegreeInstMajors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInstSigner> ElectronicDegreeInstSigners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeOperator> ElectronicDegreeOperators { get; set; }
    }
}
