//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectronicDegreeInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ElectronicDegreeInformation()
        {
            this.ElectronicDegreeInfoSigners = new HashSet<ElectronicDegreeInfoSigner>();
            this.ElectronicDegreeRequests = new HashSet<ElectronicDegreeRequest>();
        }
    
        public int ElectronicDegreeInformationId { get; set; }
        public string PeopleCodeId { get; set; }
        public string Version { get; set; }
        public string Folio { get; set; }
        public string InstitutionCode { get; set; }
        public string InstitutionName { get; set; }
        public string MajorCode { get; set; }
        public string Major { get; set; }
        public Nullable<System.DateTime> MajorStartDate { get; set; }
        public System.DateTime MajorEndDate { get; set; }
        public string StudyLevel { get; set; }
        public int AuthorizationTypeCode { get; set; }
        public string AuthorizationType { get; set; }
        public string RvoeAgreementNumber { get; set; }
        public string Curp { get; set; }
        public string Name { get; set; }
        public string FirstSurname { get; set; }
        public string SecondSurname { get; set; }
        public string Email { get; set; }
        public System.DateTime ExpeditionDate { get; set; }
        public int GraduationRequirementCode { get; set; }
        public string GraduationRequirement { get; set; }
        public Nullable<System.DateTime> ExaminationDate { get; set; }
        public Nullable<System.DateTime> ExaminationExemptionDate { get; set; }
        public bool FulfilledSocialService { get; set; }
        public int LegalBaseCode { get; set; }
        public string LegalBase { get; set; }
        public int FederalEntityCode { get; set; }
        public string FederalEntity { get; set; }
        public string OriginInstitution { get; set; }
        public int BackgroundStudyTypeCode { get; set; }
        public string BackgroundStudyType { get; set; }
        public int OriginInstFederalEntityCode { get; set; }
        public string OriginInstFederalEntity { get; set; }
        public Nullable<System.DateTime> BackgroundStudyStartDate { get; set; }
        public System.DateTime BackgroundStudyEndDate { get; set; }
        public string LicenseNumber { get; set; }
        public string Status { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
    
        public virtual ABT_USERS ABT_USERS { get; set; }
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInfoSigner> ElectronicDegreeInfoSigners { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeRequest> ElectronicDegreeRequests { get; set; }
    }
}
