//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYMENT
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ORG_CODE_ID { get; set; }
        public string POSITION { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public int RECORD_ID { get; set; }
        public string EMPLOYMENT_TYPE { get; set; }
        public string RECOMMENDATION { get; set; }
        public string RECOMMEND_EMPLOYMENT { get; set; }
        public string RESCIND_RECOMMENDATION { get; set; }
        public string AUTH_FOR_EMPLOYMENT { get; set; }
        public string EMPLOYMENT_FPT_CODE { get; set; }
        public string COURSE_RELEVANCE { get; set; }
        public string REMARKS { get; set; }
        public string ACADEMIC_YEAR_MET { get; set; }
        public string OFFCAMPUS_EMPLOY_TYPE { get; set; }
        public string EmployerName { get; set; }
    }
}
