//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACULTY
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ADVISOR { get; set; }
        public string TENURE_ELIGIBLE_YR { get; set; }
        public string TENURE_ELIGIBLE_TR { get; set; }
        public string TENURE_STATUS { get; set; }
        public string PREF_CAMPUS_1 { get; set; }
        public string PREF_BUILDING_1 { get; set; }
        public string PREF_ROOM_1 { get; set; }
        public string PREF_CAMPUS_2 { get; set; }
        public string PREF_BUILDING_2 { get; set; }
        public string PREF_ROOM_2 { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
    }
}
