//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacultyAssistantHistory
    {
        public int FacultyAssistantHistoryId { get; set; }
        public int SectionId { get; set; }
        public int AssistantId { get; set; }
        public System.DateTime StartDatetime { get; set; }
        public System.DateTime EndDatetime { get; set; }
        public Nullable<bool> CanAccessCourseHomePage { get; set; }
        public bool CanAccessActivityGrades { get; set; }
        public bool CanAccessOverallGrades { get; set; }
        public bool CanAccessViolations { get; set; }
        public bool CanAccessAttendance { get; set; }
        public bool CanAccessClassList { get; set; }
        public bool CanAccessWaitlist { get; set; }
        public bool CanSubmitOverallGrades { get; set; }
        public bool CanSetupActivities { get; set; }
        public bool CanSetupGradeMappings { get; set; }
        public bool CanAccessDashboardNotes { get; set; }
        public bool CanTakeDailyAttendance { get; set; }
        public Nullable<int> CreateById { get; set; }
        public Nullable<int> RevisionById { get; set; }
    }
}
