//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINAIDLINK
    {
        public string SSN { get; set; }
        public string YRADM { get; set; }
        public string TERM { get; set; }
        public string TRANS { get; set; }
        public string SEQNUM { get; set; }
        public int CHARGECREDITNUMBER { get; set; }
        public string TYPEINVC { get; set; }
        public string YRFIN { get; set; }
        public string PRD { get; set; }
        public string TYPETRAN { get; set; }
    }
}
