//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiscalRecordChargeMapping
    {
        public int FiscalRecordChargeMappingId { get; set; }
        public int ChargeCreditCodeId { get; set; }
        public string ProductServiceKey { get; set; }
        public string UnityKey { get; set; }
        public string Version { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string CreateOpid { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public string RevisionOpid { get; set; }
    }
}
