//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiscalRecordCatalog
    {
        public int FiscalRecordCatalogId { get; set; }
        public string CatalogName { get; set; }
        public string CatalogXml { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
    }
}
