//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FiscalRecordIssuerDefault
    {
        public int FiscalRecordIssuerDefaultId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> InvoiceOrganizationId { get; set; }
        public Nullable<int> InvoiceExpeditionId { get; set; }
        public Nullable<int> InvoiceReceiptId { get; set; }
        public string PaymentCondition { get; set; }
        public Nullable<int> CreditNoteReceiptId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public Nullable<int> ChargeCreditCodeId { get; set; }
        public Nullable<int> ChargeCreditCodeTaxId { get; set; }
    
        public virtual ABT_USERS ABT_USERS { get; set; }
        public virtual InvoiceReceipt InvoiceReceipt { get; set; }
        public virtual InvoiceExpedition InvoiceExpedition { get; set; }
        public virtual InvoiceOrganization InvoiceOrganization { get; set; }
        public virtual InvoiceReceipt InvoiceReceipt1 { get; set; }
    }
}
