//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormLayout
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormLayout()
        {
            this.ApplicationFormSettings = new HashSet<ApplicationFormSetting>();
            this.InquiryFormSettings = new HashSet<InquiryFormSetting>();
            this.SavedApplications = new HashSet<SavedApplication>();
        }
    
        public int FormLayoutId { get; set; }
        public int FormType { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string JsonDetail { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public bool IsSystemDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationFormSetting> ApplicationFormSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryFormSetting> InquiryFormSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SavedApplication> SavedApplications { get; set; }
    }
}
