//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FORMFIELD
    {
        public int FORM_ID { get; set; }
        public string FIELD_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string TABLE_NAME { get; set; }
        public string COLUMN_NAME { get; set; }
        public string SYSTEM_DEFINED { get; set; }
        public string VISIBLE { get; set; }
        public string REQUIRED { get; set; }
        public int SORT_ORDER { get; set; }
        public string FIELD_TYPE { get; set; }
        public string SQL_OBJECT { get; set; }
        public string OBJECT_TYPE { get; set; }
        public Nullable<int> PROMPT_TYPE { get; set; }
        public string REG_EX { get; set; }
        public int MAX_LENGTH { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
