//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormTemplate()
        {
            this.FormInstances = new HashSet<FormInstance>();
        }
    
        public int FormTemplateId { get; set; }
        public System.Guid TemplateGUID { get; set; }
        public byte FormType { get; set; }
        public string FormTypeDesc { get; set; }
        public string TemplateName { get; set; }
        public string TemplateDescription { get; set; }
        public string TemplateUrl { get; set; }
        public string DocumentLibraryUrl { get; set; }
        public string NamespacePrefix { get; set; }
        public bool IsActive { get; set; }
        public bool AllowSaveContinue { get; set; }
        public bool AllowAnonymousAccess { get; set; }
        public string Configuration { get; set; }
        public byte ApprovalMethod { get; set; }
        public string ApprovalMethodDesc { get; set; }
        public bool HasFee { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormInstance> FormInstances { get; set; }
        public virtual FormTemplateFee FormTemplateFee { get; set; }
    }
}
