//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIFTMATCHINGDETAIL
    {
        public int GIFTMATCHINGDETAILID { get; set; }
        public int GIFTMATCHINGID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public int PLEDGE_NUMBER { get; set; }
        public int GIFT_SEQUENCE { get; set; }
        public string ORG_CODE_ID { get; set; }
        public int ORG_PLEDGE_NUMBER { get; set; }
        public int ORG_GIFT_SEQUENCE { get; set; }
        public decimal MATCH_AMOUNT_IND { get; set; }
        public System.DateTime MATCH_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
