//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIFTPLEDGE
    {
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public int PLEDGE_NUMBER { get; set; }
        public int GIFT_SEQUENCE { get; set; }
        public string RECORD_TYPE { get; set; }
        public string GIFT_FORM { get; set; }
        public string GIFT_BATCH { get; set; }
        public System.DateTime GIFT_DATE { get; set; }
        public string GIFT_SOURCE { get; set; }
        public decimal GIFT_AMOUNT { get; set; }
        public string GIFT_TENDER { get; set; }
        public string GIFT_CHECK_NUMBER { get; set; }
        public string FISCAL_YEAR { get; set; }
        public string FISCAL_PERIOD { get; set; }
        public string JOURNAL_SOURCE { get; set; }
        public string JOURNAL_ENTRY { get; set; }
        public string POSTED_FLAG { get; set; }
        public Nullable<System.DateTime> POSTED_DATE { get; set; }
        public string PROCESS_MATCH { get; set; }
        public string COMMENTS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string REVERSED_FLAG { get; set; }
        public int REVERSED_PLEDGE_NUMBER { get; set; }
        public int REVERSED_SEQUENCE_NUMBER { get; set; }
        public Nullable<int> PaymentTransactionId { get; set; }
        public string CASE_TYPE { get; set; }
    
        public virtual PaymentTransaction PaymentTransaction { get; set; }
    }
}
