//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIFTNONCASH
    {
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public int PLEDGE_NUMBER { get; set; }
        public int GIFT_SEQUENCE { get; set; }
        public string APPRAISER_ID { get; set; }
        public string APPRAISER_NAME { get; set; }
        public Nullable<decimal> APPRAISED_VALUE { get; set; }
        public Nullable<System.DateTime> VALUATION_DATE { get; set; }
        public string PURCHASER_ID { get; set; }
        public string PURCHASER_NAME { get; set; }
        public Nullable<System.DateTime> LIQUIDATION_DATE { get; set; }
        public Nullable<decimal> LIQUIDATION_AMOUNT { get; set; }
        public string DESCRIPTION { get; set; }
        public string FIXEDASSET_FLAG { get; set; }
        public string FIXEDASSET_ID { get; set; }
        public string NONCASH_STATUS { get; set; }
        public string NONCASH_TYPE { get; set; }
        public Nullable<decimal> AMOUNT_RECEIVED { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
