//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIFTDEFAULT
    {
        public string GIFT_BATCH { get; set; }
        public string DEFAULT_OPID { get; set; }
        public string DEFAULT_TYPE { get; set; }
        public Nullable<System.DateTime> GIFT_DATE { get; set; }
        public string GIFT_SOURCE { get; set; }
        public Nullable<decimal> GIFT_AMOUNT { get; set; }
        public string GIFT_TENDER { get; set; }
        public string GIFT_ALLOCATION { get; set; }
        public string GIFT_FORM { get; set; }
        public string GIFT_PROGRAM { get; set; }
        public string GIFT_TYPE { get; set; }
        public string GIFT_CAMPAIGN { get; set; }
        public string GIFT_APPEAL { get; set; }
        public string GIFT_TEST { get; set; }
        public string SOFT_CREDIT_TYPE { get; set; }
        public string FASB_TYPE { get; set; }
        public string DEDICATION_NOTIFY { get; set; }
        public string DEDICATION_TYPE { get; set; }
        public string DEDICATION_VALUE { get; set; }
        public string SALUTATION_TYPE { get; set; }
        public string PROJECT_ID { get; set; }
        public string ACTIVITY_ID { get; set; }
        public string BENEFIT_TYPE { get; set; }
        public string METHOD_HOW { get; set; }
        public string METHOD_WHO { get; set; }
        public string METHOD_WHEN { get; set; }
        public string RECEIPT_PRINT { get; set; }
        public string ACKNOWLEDGE_PRINT { get; set; }
        public string ACKNOWLEDGE_TYPE { get; set; }
        public string ACKNOWLEDGE_RESPID { get; set; }
        public string ACKNOWLEDGE_ADD_TYPE { get; set; }
        public Nullable<System.DateTime> ACKNOWLEDGE_DATE { get; set; }
        public string SOLICITOR_CODE { get; set; }
        public string SOLICITOR_METHOD { get; set; }
        public Nullable<int> PERCENT_OF_RESP { get; set; }
        public string PLEDGE_STATUS { get; set; }
        public string PLEDGE_TERM { get; set; }
        public string PLEDGE_TYPE { get; set; }
        public Nullable<int> NUMBER_MONTHS { get; set; }
        public Nullable<int> NUMBER_PAYMENTS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
