//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GIFTCREDITDETAIL
    {
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public int PLEDGE_NUMBER { get; set; }
        public int GIFT_SEQUENCE { get; set; }
        public int DETAIL_SEQUENCE { get; set; }
        public string ASSOCIATED_ID { get; set; }
        public decimal GIFT_AMOUNT { get; set; }
        public string GIFT_YEAR { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public int GIFTCREDITDETAIL_ID { get; set; }
        public System.DateTime GIFTCREDIT_DATE { get; set; }
        public string GIFTCREDIT_CAMPAIGN { get; set; }
        public string GIFTCREDIT_APPEAL { get; set; }
        public string GIFTCREDIT_PROJECT { get; set; }
    }
}
