//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL00100
    {
        public int ACTINDX { get; set; }
        public string ACTNUMBR_1 { get; set; }
        public string ACTNUMBR_2 { get; set; }
        public string ACTNUMBR_3 { get; set; }
        public string ACTNUMBR_4 { get; set; }
        public string ACTNUMBR_5 { get; set; }
        public string ACTNUMBR_6 { get; set; }
        public string ACTNUMBR_7 { get; set; }
        public string ACTNUMBR_8 { get; set; }
        public string ACTNUMBR_9 { get; set; }
        public string ACTNUMBR_10 { get; set; }
        public string ACTALIAS { get; set; }
        public string MNACSGMT { get; set; }
        public short ACCTTYPE { get; set; }
        public string ACTDESCR { get; set; }
        public short PSTNGTYP { get; set; }
        public short ACCATNUM { get; set; }
        public byte ACTIVE { get; set; }
        public short TPCLBLNC { get; set; }
        public short DECPLACS { get; set; }
        public short FXDORVAR { get; set; }
        public short BALFRCLC { get; set; }
        public byte[] DSPLKUPS { get; set; }
        public short CNVRMTHD { get; set; }
        public decimal HSTRCLRT { get; set; }
        public decimal NOTEINDX { get; set; }
        public System.DateTime CREATDDT { get; set; }
        public System.DateTime MODIFDT { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public string USRDEFS1 { get; set; }
        public string USRDEFS2 { get; set; }
        public short POSTSLSIN { get; set; }
        public short POSTIVIN { get; set; }
        public short POSTPURCHIN { get; set; }
        public short POSTPRIN { get; set; }
        public byte ADJINFL { get; set; }
        public int INFLAREV { get; set; }
        public int INFLAEQU { get; set; }
        public byte ACCTENTR { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
