//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRADEVALUE
    {
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string GRADE { get; set; }
        public decimal QUALITY_POINTS { get; set; }
        public string COUNT_ATTEMPTED { get; set; }
        public string COUNT_EARNED { get; set; }
        public string COUNT_TOTAL { get; set; }
        public string COUNT_TRANSFER { get; set; }
        public string COUNT_GPA { get; set; }
        public string COUNT_CONTACT_HR { get; set; }
        public string GRADE_RANK { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string INCLUDE_AS_REPEAT { get; set; }
        public string PASS_FAIL { get; set; }
        public string GRADE_DISPLAY { get; set; }
        public string ALLOW_WEB_ENTRY { get; set; }
        public string CREDIT_TYPE { get; set; }
        public string WITHDRAWN_GRADE { get; set; }
        public int GradeValueId { get; set; }
        public bool IsMappable { get; set; }
    }
}
