//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class GreatPlainsPhone
    {
        public int GreatPlainsPhoneId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public string CreateOpId { get; set; }
        public string CreateTerminal { get; set; }
        public System.DateTime RevisionDateTime { get; set; }
        public string RevisionOpId { get; set; }
        public string RevisionTerminal { get; set; }
    }
}
