//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdentityRoleClaim
    {
        public int IdentityRoleClaimId { get; set; }
        public int IdentityRoleId { get; set; }
        public int IdentityClaimId { get; set; }
    
        public virtual IdentityClaim IdentityClaim { get; set; }
        public virtual IdentityRole IdentityRole { get; set; }
    }
}
