//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_NOTIFICATIONS_PROCEDURES
    {
        public string NOTIFICATION_CODE { get; set; }
        public string NOTIFICATION_PROC { get; set; }
        public string NOTIFICATION_STATUS { get; set; }
    }
}
