//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_NOTIFICATIONS
    {
        public string NOTIFICATION_CODE { get; set; }
        public string NOTIFICATION_DESC { get; set; }
        public string NOTIFICATION_STATUS { get; set; }
        public string EMAIL_SUBJECT { get; set; }
        public string EMAIL_BODY { get; set; }
        public Nullable<int> EMAIL_BODY_FORMAT { get; set; }
        public string EMAIL_SENDER { get; set; }
        public Nullable<int> HIDE_RECIPIENTS { get; set; }
        public string NOTIFICATION_TABLE { get; set; }
        public string NOTIFICATION_CRITERIA { get; set; }
        public string RECORD_UNIQUE_ID_FORMAT { get; set; }
        public string RECORD_OWNER_TYPE { get; set; }
        public string RECORD_OWNER_FIELD { get; set; }
        public string EMAIL_ATTACHMENT1 { get; set; }
        public string EMAIL_ATTACHMENT2 { get; set; }
        public string EMAIL_ATTACHMENT3 { get; set; }
        public string WORD_PATH { get; set; }
    }
}
