//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMS_NOTIFICATION_RECIPIENTS
    {
        public string NOTIFICATION_CODE { get; set; }
        public string RECIPIENT_TYPE { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string EMAIL_ADDRESS { get; set; }
    }
}
