//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryProgram
    {
        public int InquiryProgramId { get; set; }
        public int InquiryId { get; set; }
        public Nullable<int> ProgramOfStudyId { get; set; }
        public Nullable<int> FullTimePartTime { get; set; }
    
        public virtual Inquiry Inquiry { get; set; }
        public virtual ProgramOfStudy ProgramOfStudy { get; set; }
    }
}
