//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryActivity
    {
        public int InquiryActivityId { get; set; }
        public int InquiryId { get; set; }
        public int Activity { get; set; }
        public Nullable<int> Position { get; set; }
        public decimal HoursPerWeek { get; set; }
        public int WeeksPerYear { get; set; }
        public int NumberOfYears { get; set; }
        public bool ParticipatedGrade09 { get; set; }
        public bool ParticipatedGrade10 { get; set; }
        public bool ParticipatedGrade11 { get; set; }
        public bool ParticipatedGrade12 { get; set; }
        public bool ParticipatedPostSecondary { get; set; }
    
        public virtual Inquiry Inquiry { get; set; }
    }
}
