//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquirySourceSetting
    {
        public int InquirySourceSettingId { get; set; }
        public int InquiryFormSettingId { get; set; }
        public int SourceId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
    
        public virtual InquiryFormSetting InquiryFormSetting { get; set; }
    }
}
