//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InquiryFormSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InquiryFormSetting()
        {
            this.Inquiries = new HashSet<Inquiry>();
            this.InquiryActivitySettings = new HashSet<InquiryActivitySetting>();
            this.InquiryActivityTypeSettings = new HashSet<InquiryActivityTypeSetting>();
            this.InquiryAddressSettings = new HashSet<InquiryAddressSetting>();
            this.InquiryApprovers = new HashSet<InquiryApprover>();
            this.InquiryCollegeAttendSettings = new HashSet<InquiryCollegeAttendSetting>();
            this.InquiryCounselorSettings = new HashSet<InquiryCounselorSetting>();
            this.InquiryInterestSettings = new HashSet<InquiryInterestSetting>();
            this.InquiryPeriodSettings = new HashSet<InquiryPeriodSetting>();
            this.InquiryPhoneTypeSettings = new HashSet<InquiryPhoneTypeSetting>();
            this.InquiryProgramSettings = new HashSet<InquiryProgramSetting>();
            this.InquirySourceSettings = new HashSet<InquirySourceSetting>();
        }
    
        public int InquiryFormSettingId { get; set; }
        public string InquiryFormName { get; set; }
        public string InquiryFormDescription { get; set; }
        public bool IsActive { get; set; }
        public byte PageStyle { get; set; }
        public int DefaultInquiryStatusId { get; set; }
        public int DefaultCampusId { get; set; }
        public bool ProcessAutomatically { get; set; }
        public bool CheckDuplicates { get; set; }
        public bool ValidateEtsCode { get; set; }
        public byte PrefixState { get; set; }
        public byte MiddleNameState { get; set; }
        public byte SuffixState { get; set; }
        public byte NicknameState { get; set; }
        public byte FormerLastNameState { get; set; }
        public byte Line2State { get; set; }
        public byte Line3State { get; set; }
        public byte StateProvinceIdState { get; set; }
        public byte PostalCodeState { get; set; }
        public byte CountyState { get; set; }
        public byte EmailState { get; set; }
        public bool IncludePhone { get; set; }
        public byte PeriodState { get; set; }
        public byte ProgramOfStudyState { get; set; }
        public byte FullTimePartTimeState { get; set; }
        public byte CollegeAttendStatusState { get; set; }
        public byte IsSeekingDegreeState { get; set; }
        public byte FinancialAidState { get; set; }
        public byte ExtraCurricularState { get; set; }
        public byte InterestIdState { get; set; }
        public byte BirthDateState { get; set; }
        public byte GenderState { get; set; }
        public byte EthnicityState { get; set; }
        public byte MaritalStatusState { get; set; }
        public byte ReligionState { get; set; }
        public byte VeteranStatusState { get; set; }
        public byte IsRetiredState { get; set; }
        public bool IncludeIpeds { get; set; }
        public byte PrimaryCitizenshipState { get; set; }
        public byte SecondaryCitizenshipState { get; set; }
        public byte VisaState { get; set; }
        public byte CountryOfBirthState { get; set; }
        public byte PrimaryLanguageState { get; set; }
        public byte SecondaryLanguageState { get; set; }
        public byte MonthsInCountryState { get; set; }
        public byte GovernmentIdState { get; set; }
        public byte SevisNumberState { get; set; }
        public byte DriversLicenseNumberState { get; set; }
        public byte DriversLicenseStateState { get; set; }
        public byte VisaNumberState { get; set; }
        public byte VisaCountryIssuedState { get; set; }
        public byte VisaExpirationDateState { get; set; }
        public byte PassportNumberState { get; set; }
        public byte PassportCountryIssuedState { get; set; }
        public byte PassportExpirationDateState { get; set; }
        public byte PortOfEntryState { get; set; }
        public byte DateOfEntryState { get; set; }
        public byte CriminalConvictionsState { get; set; }
        public byte SourceIdState { get; set; }
        public bool IncludeActivities { get; set; }
        public byte PositionState { get; set; }
        public byte HoursPerWeekState { get; set; }
        public byte WeeksPerYearState { get; set; }
        public byte NumberOfYearsState { get; set; }
        public bool IncludeParticipatedGrade09 { get; set; }
        public bool IncludeParticipatedGrade10 { get; set; }
        public bool IncludeParticipatedGrade11 { get; set; }
        public bool IncludeParticipatedGrade12 { get; set; }
        public bool IncludePostSecondary { get; set; }
        public byte EducationState { get; set; }
        public byte EtsCodeState { get; set; }
        public byte FiceCodeState { get; set; }
        public byte InstitutionNameState { get; set; }
        public byte InstitutionCityState { get; set; }
        public byte InstitutionStateProvinceState { get; set; }
        public byte InstitutionCountryIdState { get; set; }
        public byte StartDateState { get; set; }
        public byte EndDateState { get; set; }
        public byte CurriculumIdState { get; set; }
        public byte DegreeIdState { get; set; }
        public byte HonorsIdState { get; set; }
        public string LayoutFileName { get; set; }
        public byte CounselorState { get; set; }
        public bool AllowOtherSource { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public byte LastNamePrefixState { get; set; }
        public byte Line4State { get; set; }
        public byte HouseNumberState { get; set; }
        public Nullable<int> DefaultEmailTypeId { get; set; }
        public int FormLayoutId { get; set; }
    
        public virtual CODE_EMAILTYPE CODE_EMAILTYPE { get; set; }
        public virtual FormLayout FormLayout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inquiry> Inquiries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryActivitySetting> InquiryActivitySettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryActivityTypeSetting> InquiryActivityTypeSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryAddressSetting> InquiryAddressSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryApprover> InquiryApprovers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryCollegeAttendSetting> InquiryCollegeAttendSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryCounselorSetting> InquiryCounselorSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryInterestSetting> InquiryInterestSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryPeriodSetting> InquiryPeriodSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryPhoneTypeSetting> InquiryPhoneTypeSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryProgramSetting> InquiryProgramSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquirySourceSetting> InquirySourceSettings { get; set; }
    }
}
