//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inquiry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inquiry()
        {
            this.InquiryActivities = new HashSet<InquiryActivity>();
            this.InquiryEducations = new HashSet<InquiryEducation>();
            this.InquiryEthnicities = new HashSet<InquiryEthnicity>();
            this.InquiryInterests = new HashSet<InquiryInterest>();
            this.InquiryPhones = new HashSet<InquiryPhone>();
            this.InquiryPrograms = new HashSet<InquiryProgram>();
            this.InquirySources = new HashSet<InquirySource>();
            this.InquiryUserDefineds = new HashSet<InquiryUserDefined>();
        }
    
        public int InquiryId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public byte Status { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Suffix { get; set; }
        public string Nickname { get; set; }
        public string FormerLastName { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
        public string Line1 { get; set; }
        public string Line2 { get; set; }
        public string Line3 { get; set; }
        public string City { get; set; }
        public Nullable<int> StateProvinceId { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> County { get; set; }
        public Nullable<int> Country { get; set; }
        public string DaytimePhoneNumber { get; set; }
        public string EveningPhoneNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<int> Ethnicity { get; set; }
        public Nullable<int> MaritalStatus { get; set; }
        public Nullable<int> Religion { get; set; }
        public Nullable<int> VeteranStatus { get; set; }
        public Nullable<bool> IsRetired { get; set; }
        public Nullable<int> PrimaryCitizenship { get; set; }
        public Nullable<int> SecondaryCitizenship { get; set; }
        public Nullable<int> CountryOfBirth { get; set; }
        public Nullable<int> PrimaryLanguage { get; set; }
        public Nullable<int> SecondaryLanguage { get; set; }
        public Nullable<short> MonthsInCountry { get; set; }
        public Nullable<int> Visa { get; set; }
        public string VisaNumber { get; set; }
        public Nullable<int> VisaCountryIssued { get; set; }
        public Nullable<System.DateTime> VisaExpirationDate { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<int> PassportCountryIssued { get; set; }
        public Nullable<System.DateTime> PassportExpirationDate { get; set; }
        public string PortOfEntry { get; set; }
        public Nullable<System.DateTime> DateOfEntry { get; set; }
        public Nullable<bool> CriminalConviction { get; set; }
        public string GovernmentId { get; set; }
        public string SevisNumber { get; set; }
        public string DriversLicenseNumber { get; set; }
        public Nullable<int> DriversLicenseState { get; set; }
        public Nullable<short> AcademicYear { get; set; }
        public Nullable<int> TermPeriodId { get; set; }
        public Nullable<int> SessionPeriodId { get; set; }
        public Nullable<int> CollegeAttendStatus { get; set; }
        public bool IsSeekingDegree { get; set; }
        public bool IsInterestedInExtraCurricular { get; set; }
        public bool IsInterestedInFinancialAid { get; set; }
        public int InquiryStatusId { get; set; }
        public int CampusId { get; set; }
        public Nullable<int> PrimaryPhoneId { get; set; }
        public Nullable<int> CounselorId { get; set; }
        public string OtherSource { get; set; }
        public int InquiryFormSettingId { get; set; }
        public string LastNamePrefix { get; set; }
        public string Line4 { get; set; }
        public string HouseNumber { get; set; }
    
        public virtual InquiryFormSetting InquiryFormSetting { get; set; }
        public virtual InquiryPhone InquiryPhone { get; set; }
        public virtual TermPeriod TermPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryActivity> InquiryActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryEducation> InquiryEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryEthnicity> InquiryEthnicities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryInterest> InquiryInterests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryPhone> InquiryPhones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryProgram> InquiryPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquirySource> InquirySources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryUserDefined> InquiryUserDefineds { get; set; }
    }
}
