//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallmentChargeCredit
    {
        public int InstallmentChargeCreditId { get; set; }
        public int InstallmentRuleId { get; set; }
        public int ChargeCreditCodeId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Create_Time { get; set; }
        public string Create_Opid { get; set; }
        public string Create_Terminal { get; set; }
        public System.DateTime Revision_Date { get; set; }
        public System.DateTime Revision_Time { get; set; }
        public string Revision_Opid { get; set; }
        public string Revision_Terminal { get; set; }
    
        public virtual InstallmentRule InstallmentRule { get; set; }
    }
}
