//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class INTEGRATIONINFO
    {
        public string INTEGRATION_NAME { get; set; }
        public string LABEL_NAME { get; set; }
        public string TABLE_NAME { get; set; }
        public string SETTING { get; set; }
    }
}
