//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePreferredTaxpayer
    {
        public int InvoicePreferredTaxpayerId { get; set; }
        public string PeopleOrgCodeId { get; set; }
        public Nullable<int> InvoiceTaxpayerId { get; set; }
        public string ReceiverEmail { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string CFDIUsageCode { get; set; }
        public string CFDIUsageDesc { get; set; }
    
        public virtual InvoiceTaxpayer InvoiceTaxpayer { get; set; }
    }
}
