//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceOrganization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceOrganization()
        {
            this.FiscalRecordIssuerDefaults = new HashSet<FiscalRecordIssuerDefault>();
            this.InvoiceExpeditions = new HashSet<InvoiceExpedition>();
            this.InvoiceHeaders = new HashSet<InvoiceHeader>();
            this.InvoiceOrganizationTaxRegimen = new HashSet<InvoiceOrganizationTaxRegiman>();
            this.InvoiceReceipts = new HashSet<InvoiceReceipt>();
        }
    
        public int InvoiceOrganizationId { get; set; }
        public string TaxpayerId { get; set; }
        public string CorporateName { get; set; }
        public string StreetName { get; set; }
        public string StreetNumber { get; set; }
        public string ApartmentNumber { get; set; }
        public string Neighborhood { get; set; }
        public string Location { get; set; }
        public string Reference { get; set; }
        public Nullable<int> CountyId { get; set; }
        public Nullable<int> StateProvinceId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string PostalCode { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Create_Time { get; set; }
        public string Create_Opid { get; set; }
        public string Create_Terminal { get; set; }
        public System.DateTime Revision_Date { get; set; }
        public System.DateTime Revision_Time { get; set; }
        public string Revision_Opid { get; set; }
        public string Revision_Terminal { get; set; }
        public string IssuerEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiscalRecordIssuerDefault> FiscalRecordIssuerDefaults { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceExpedition> InvoiceExpeditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceHeader> InvoiceHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceOrganizationTaxRegiman> InvoiceOrganizationTaxRegimen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceReceipt> InvoiceReceipts { get; set; }
    }
}
