//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicePaymentMethod
    {
        public int InvoicePaymentMethodId { get; set; }
        public int InvoiceHeaderId { get; set; }
        public int PaymentMethodId { get; set; }
        public byte SortOrder { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual CODE_PAYMENTMETHOD CODE_PAYMENTMETHOD { get; set; }
        public virtual InvoiceHeader InvoiceHeader { get; set; }
    }
}
