//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceOrganizationTaxRegiman
    {
        public int InvoiceOrgTaxRegimenId { get; set; }
        public int InvoiceOrganizationId { get; set; }
        public int TaxRegimenId { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        public virtual CODE_TAXREGIMEN CODE_TAXREGIMEN { get; set; }
        public virtual InvoiceOrganization InvoiceOrganization { get; set; }
    }
}
