//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceCertificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceCertificate()
        {
            this.InvoiceCertificateFiles = new HashSet<InvoiceCertificateFile>();
        }
    
        public int InvoiceCertificateId { get; set; }
        public int InvoiceHeaderId { get; set; }
        public System.DateTime ApprovedDatetime { get; set; }
        public string InvoiceXml { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual InvoiceHeader InvoiceHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceCertificateFile> InvoiceCertificateFiles { get; set; }
    }
}
