//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITB_PaymentLog
    {
        public int Id { get; set; }
        public string PEOPLE_ID { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string Currency { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string PaymentProvider { get; set; }
        public string PaymentMethod { get; set; }
        public string PaymentReference { get; set; }
        public Nullable<int> CashReceiptNumber { get; set; }
        public string SIMS { get; set; }
        public Nullable<bool> InsertedInPC { get; set; }
    }
}
