//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LDISPEXPORTHEADER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LDISPEXPORTHEADER()
        {
            this.LDISPEXPORTFILEHISTORies = new HashSet<LDISPEXPORTFILEHISTORY>();
        }
    
        public int EXPORT_ID { get; set; }
        public System.DateTime EXPORT_START_DATE { get; set; }
        public System.DateTime EXPORT_START_TIME { get; set; }
        public Nullable<System.DateTime> EXPORT_END_DATE { get; set; }
        public Nullable<System.DateTime> EXPORT_END_TIME { get; set; }
        public string EXPORT_SUCCESSFUL { get; set; }
        public string STATUS_MESSAGE { get; set; }
        public string EXPORT_LOCATION { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LDISPEXPORTFILEHISTORY> LDISPEXPORTFILEHISTORies { get; set; }
    }
}
