//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakePaymentPeriod
    {
        public int MakePaymentPeriodId { get; set; }
        public Nullable<int> TermPeriodId { get; set; }
        public Nullable<int> SessionPeriodId { get; set; }
        public System.DateTime CreatedOn { get; set; }
    
        public virtual TermPeriod TermPeriod { get; set; }
    }
}
