//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSLCEnrollment
    {
        public int NSLCEnrollmentId { get; set; }
        public string PeopleCodeId { get; set; }
        public string AcademicYear { get; set; }
        public string AcademicTerm { get; set; }
        public string AcademicSession { get; set; }
        public string BranchCode { get; set; }
        public System.DateTime RunDate { get; set; }
        public string ReportFlag { get; set; }
        public string Program { get; set; }
        public string Degree { get; set; }
        public string Curriculum { get; set; }
        public string EnrollmentStatus { get; set; }
        public Nullable<System.DateTime> EnrollmentStatusDate { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        public virtual NSLCDETAIL NSLCDETAIL { get; set; }
    }
}
