//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSLCDETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NSLCDETAIL()
        {
            this.NSLCEnrollments = new HashSet<NSLCEnrollment>();
        }
    
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string BRANCH_CODE { get; set; }
        public System.DateTime RUN_DATE { get; set; }
        public string REPORT_FLAG { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string GOVERNMENT_ID { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_INITIAL { get; set; }
        public string LAST_NAME { get; set; }
        public string SUFFIX { get; set; }
        public string PREV_GOV_ID { get; set; }
        public string FORMER_LAST_NAME { get; set; }
        public decimal CREDITS { get; set; }
        public string ENROLLMENT_STATUS { get; set; }
        public Nullable<System.DateTime> ENROLLMENT_STATUS_DATE { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string COUNTRY { get; set; }
        public Nullable<System.DateTime> ANTICIPATED_GRAD_DATE { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public System.DateTime TERM_START_DATE { get; set; }
        public System.DateTime TERM_END_DATE { get; set; }
        public string GRADUATE_LEVEL_INDICATOR { get; set; }
        public string DATA_BLOCK_INDICATOR { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string Curriculum_Desc { get; set; }
        public string Middle_Name { get; set; }
        public string Class_Level { get; set; }
        public string Email_Address { get; set; }
        public string Gender { get; set; }
        public string ProgramIndicator { get; set; }
        public string Program1CipCode { get; set; }
        public Nullable<int> Program1CipYear { get; set; }
        public string Program1CredentialLevel { get; set; }
        public string Program1PublishedLength { get; set; }
        public string Program1LengthMeasurement { get; set; }
        public string Program1WeeksInTitleIVAcaYear { get; set; }
        public Nullable<System.DateTime> Program1BeginDate { get; set; }
        public string Program1SpecialIndicator { get; set; }
        public string Program1EnrollmentStatus { get; set; }
        public Nullable<System.DateTime> Program1EnrollmentStatusDate { get; set; }
        public string Program2CipCode { get; set; }
        public Nullable<int> Program2CipYear { get; set; }
        public string Program2CredentialLevel { get; set; }
        public string Program2PublishedLength { get; set; }
        public string Program2LengthMeasurement { get; set; }
        public string Program2WeeksInTitleIVAcaYear { get; set; }
        public Nullable<System.DateTime> Program2BeginDate { get; set; }
        public string Program2SpecialIndicator { get; set; }
        public string Program2EnrollmentStatus { get; set; }
        public Nullable<System.DateTime> Program2EnrollmentStatusDate { get; set; }
        public string Program3CipCode { get; set; }
        public Nullable<int> Program3CipYear { get; set; }
        public string Program3CredentialLevel { get; set; }
        public string Program3PublishedLength { get; set; }
        public string Program3LengthMeasurement { get; set; }
        public string Program3WeeksInTitleIVAcaYear { get; set; }
        public Nullable<System.DateTime> Program3BeginDate { get; set; }
        public string Program3SpecialIndicator { get; set; }
        public string Program3EnrollmentStatus { get; set; }
        public Nullable<System.DateTime> Program3EnrollmentStatusDate { get; set; }
        public string Program4CipCode { get; set; }
        public Nullable<int> Program4CipYear { get; set; }
        public string Program4CredentialLevel { get; set; }
        public string Program4PublishedLength { get; set; }
        public string Program4LengthMeasurement { get; set; }
        public string Program4WeeksInTitleIVAcaYear { get; set; }
        public Nullable<System.DateTime> Program4BeginDate { get; set; }
        public string Program4SpecialIndicator { get; set; }
        public string Program4EnrollmentStatus { get; set; }
        public Nullable<System.DateTime> Program4EnrollmentStatusDate { get; set; }
        public string Program5CipCode { get; set; }
        public Nullable<int> Program5CipYear { get; set; }
        public string Program5CredentialLevel { get; set; }
        public string Program5PublishedLength { get; set; }
        public string Program5LengthMeasurement { get; set; }
        public string Program5WeeksInTitleIVAcaYear { get; set; }
        public Nullable<System.DateTime> Program5BeginDate { get; set; }
        public string Program5SpecialIndicator { get; set; }
        public string Program5EnrollmentStatus { get; set; }
        public Nullable<System.DateTime> Program5EnrollmentStatusDate { get; set; }
        public string Program6CipCode { get; set; }
        public Nullable<int> Program6CipYear { get; set; }
        public string Program6CredentialLevel { get; set; }
        public string Program6PublishedLength { get; set; }
        public string Program6LengthMeasurement { get; set; }
        public string Program6WeeksInTitleIVAcaYear { get; set; }
        public Nullable<System.DateTime> Program6BeginDate { get; set; }
        public string Program6SpecialIndicator { get; set; }
        public string Program6EnrollmentStatus { get; set; }
        public Nullable<System.DateTime> Program6EnrollmentStatusDate { get; set; }
        public bool IsTrialRun { get; set; }
        public string Program1Major { get; set; }
        public string Program2Major { get; set; }
        public string Program3Major { get; set; }
        public string Program4Major { get; set; }
        public string Program5Major { get; set; }
        public string Program6Major { get; set; }
    
        public virtual CODE_PROGRAMCREDENTIALLEVEL CODE_PROGRAMCREDENTIALLEVEL { get; set; }
        public virtual CODE_PROGRAMCREDENTIALLEVEL CODE_PROGRAMCREDENTIALLEVEL1 { get; set; }
        public virtual CODE_PROGRAMCREDENTIALLEVEL CODE_PROGRAMCREDENTIALLEVEL2 { get; set; }
        public virtual CODE_PROGRAMCREDENTIALLEVEL CODE_PROGRAMCREDENTIALLEVEL3 { get; set; }
        public virtual CODE_PROGRAMCREDENTIALLEVEL CODE_PROGRAMCREDENTIALLEVEL4 { get; set; }
        public virtual CODE_PROGRAMCREDENTIALLEVEL CODE_PROGRAMCREDENTIALLEVEL5 { get; set; }
        public virtual CODE_SPECIALPROGRAMINDICATOR CODE_SPECIALPROGRAMINDICATOR { get; set; }
        public virtual CODE_SPECIALPROGRAMINDICATOR CODE_SPECIALPROGRAMINDICATOR1 { get; set; }
        public virtual CODE_SPECIALPROGRAMINDICATOR CODE_SPECIALPROGRAMINDICATOR2 { get; set; }
        public virtual CODE_SPECIALPROGRAMINDICATOR CODE_SPECIALPROGRAMINDICATOR3 { get; set; }
        public virtual CODE_SPECIALPROGRAMINDICATOR CODE_SPECIALPROGRAMINDICATOR4 { get; set; }
        public virtual CODE_SPECIALPROGRAMINDICATOR CODE_SPECIALPROGRAMINDICATOR5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NSLCEnrollment> NSLCEnrollments { get; set; }
    }
}
