//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSLCTRAILER
    {
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string BRANCH_CODE { get; set; }
        public System.DateTime RUN_DATE { get; set; }
        public string REPORT_FLAG { get; set; }
        public int NUMBER_OF_F { get; set; }
        public int NUMBER_OF_H { get; set; }
        public int NUMBER_OF_L { get; set; }
        public int NUMBER_OF_W { get; set; }
        public int NUMBER_OF_G { get; set; }
        public int NUMBER_OF_A { get; set; }
        public int NUMBER_OF_X { get; set; }
        public int NUMBER_OF_D { get; set; }
        public int TOTAL_RECORD_COUNT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public Nullable<int> NUMBER_OF_Q { get; set; }
    }
}
