//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORGANIZATIONMATCHING
    {
        public string ORG_CODE_ID { get; set; }
        public string MATCH_TYPE { get; set; }
        public Nullable<decimal> MATCH_FACTOR { get; set; }
        public Nullable<decimal> MAX_ANNUAL_AMT { get; set; }
        public Nullable<decimal> MAX_LIFE_AMT { get; set; }
        public Nullable<decimal> MAX_GIFT_AMT { get; set; }
        public Nullable<decimal> MIN_GIFT_AMT { get; set; }
        public string RESTRICTION { get; set; }
        public string COMMENTS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
