//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationPhone
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizationPhone()
        {
            this.ORGANIZATIONs = new HashSet<ORGANIZATION>();
        }
    
        public int OrganizationPhoneId { get; set; }
        public int OrganizationId { get; set; }
        public int CountryId { get; set; }
        public string PhoneNumber { get; set; }
        public string Description { get; set; }
        public Nullable<int> DoNotCallReason { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Create_Time { get; set; }
        public string Create_Opid { get; set; }
        public string Create_Terminal { get; set; }
        public System.DateTime Revision_Date { get; set; }
        public System.DateTime Revision_Time { get; set; }
        public string Revision_Opid { get; set; }
        public string Revision_Terminal { get; set; }
        public string PhoneType { get; set; }
    
        public virtual CODE_ORGPHONETYPE CODE_ORGPHONETYPE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORGANIZATION> ORGANIZATIONs { get; set; }
    }
}
