//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentTransactionGiftCampaign
    {
        public int PaymentTransactionId { get; set; }
        public int GiftCampaignId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public int GiftBatchHeaderId { get; set; }
    
        public virtual PaymentTransaction PaymentTransaction { get; set; }
    }
}
