//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PBCATEDT
    {
        public string PBE_NAME { get; set; }
        public string PBE_EDIT { get; set; }
        public short PBE_TYPE { get; set; }
        public Nullable<int> PBE_CNTR { get; set; }
        public short PBE_SEQN { get; set; }
        public Nullable<int> PBE_FLAG { get; set; }
        public string PBE_WORK { get; set; }
    }
}
