//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleDashboardMessage
    {
        public int PeopleDashboardMessageId { get; set; }
        public int DashboardMessageId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual DashboardMessage DashboardMessage { get; set; }
    }
}
