//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEOPLESCHOLARSHIP
    {
        public int PEOPLESCHOLARSHIP_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string SCHOLARSHIP_ID { get; set; }
        public string DEPARTMENT { get; set; }
        public string LEVEL { get; set; }
        public string STATUS { get; set; }
        public System.DateTime STATUS_DATE { get; set; }
        public decimal APPLIED_AMOUNT { get; set; }
        public decimal AWARDED_AMOUNT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
