//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeopleScholarshipOfferingReq
    {
        public int PeopleScholarshipOfferingReqId { get; set; }
        public int ScholarshipApplicationId { get; set; }
        public int ScholarshipOfferingReqId { get; set; }
        public Nullable<int> ActionScheduleId { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        public virtual ACTIONSCHEDULE ACTIONSCHEDULE { get; set; }
        public virtual ScholarshipApplication ScholarshipApplication { get; set; }
        public virtual ScholarshipOfferingReq ScholarshipOfferingReq { get; set; }
    }
}
