//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonPhoneDateRange
    {
        public int PersonPhoneId { get; set; }
        public byte FromMonth { get; set; }
        public byte FromDay { get; set; }
        public byte ToMonth { get; set; }
        public byte ToDay { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
    
        public virtual PersonPhone PersonPhone { get; set; }
    }
}
