//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Person()
        {
            this.BulkAccounts = new HashSet<BulkAccount>();
            this.ETranscriptOrders = new HashSet<ETranscriptOrder>();
            this.GenderIdentityHistories = new HashSet<GenderIdentityHistory>();
            this.ElectronicDegreeInformations = new HashSet<ElectronicDegreeInformation>();
            this.PeopleEmergencyHistories = new HashSet<PeopleEmergencyHistory>();
            this.Reported1098TInformationDetail = new HashSet<Reported1098TInformationDetail>();
            this.Reported1098TPeriodSummary = new HashSet<Reported1098TPeriodSummary>();
            this.ScholarshipOfferingSchedActions = new HashSet<ScholarshipOfferingSchedAction>();
            this.StudentCertificates = new HashSet<StudentCertificate>();
            this.TermLevelCreditLimits = new HashSet<TermLevelCreditLimit>();
        }
    
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string PREVIOUS_ID { get; set; }
        public string GOVERNMENT_ID { get; set; }
        public string PREV_GOV_ID { get; set; }
        public string PREFIX { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string SUFFIX { get; set; }
        public string NICKNAME { get; set; }
        public string PREFERRED_ADD { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string BIRTH_CITY { get; set; }
        public string BIRTH_STATE { get; set; }
        public string BIRTH_ZIP_CODE { get; set; }
        public string BIRTH_COUNTRY { get; set; }
        public string BIRTH_COUNTY { get; set; }
        public Nullable<System.DateTime> DECEASED_DATE { get; set; }
        public string DECEASED_FLAG { get; set; }
        public string RELEASE_INFO { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string TAX_ID { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> PrimaryPhoneId { get; set; }
        public string Last_Name_Prefix { get; set; }
        public string LegalName { get; set; }
        public string DisplayName { get; set; }
        public string GenderIdentity { get; set; }
        public string Pronoun { get; set; }
        public Nullable<int> PrimaryEmailId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BulkAccount> BulkAccounts { get; set; }
        public virtual EmailAddress EmailAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ETranscriptOrder> ETranscriptOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GenderIdentityHistory> GenderIdentityHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInformation> ElectronicDegreeInformations { get; set; }
        public virtual PersonPhone PersonPhone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeopleEmergencyHistory> PeopleEmergencyHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reported1098TInformationDetail> Reported1098TInformationDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reported1098TPeriodSummary> Reported1098TPeriodSummary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipOfferingSchedAction> ScholarshipOfferingSchedActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCertificate> StudentCertificates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TermLevelCreditLimit> TermLevelCreditLimits { get; set; }
    }
}
