//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonEthnicityHistory
    {
        public int PersonEthnicityHistoryId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> IpedsEthnicityId { get; set; }
        public int IpedsFederalCategoryId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual CODE_IPEDSETHNICITY CODE_IPEDSETHNICITY { get; set; }
        public virtual IpedsFederalCategory IpedsFederalCategory { get; set; }
    }
}
