//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PersonUser()
        {
            this.DeletedPersonTypes = new HashSet<DeletedPersonType>();
        }
    
        public int PersonId { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime RevisionDate { get; set; }
        public Nullable<int> UserStoreId { get; set; }
        public string NonQualifiedUserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeletedPersonType> DeletedPersonTypes { get; set; }
        public virtual UserStore UserStore { get; set; }
    }
}
