//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFIAcademic
    {
        public int Id { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string POE { get; set; }
        public string CLASS_LEVEL { get; set; }
        public string FULL_PART { get; set; }
        public decimal CREDITS { get; set; }
        public Nullable<System.DateTime> SEPARATION_DATE { get; set; }
        public string AWARD_VALUE { get; set; }
        public string ACADEMICYEARTERMSORT { get; set; }
        public bool UPDATED { get; set; }
        public string FULL_PART_NON_WITHDRAWN { get; set; }
    
        public virtual PFIPROCESSID PFIPROCESSID { get; set; }
    }
}
