//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFIMAPPING
    {
        public int RECORD_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string PF_COLUMN_NAME { get; set; }
        public string PC_TABLE_NAME { get; set; }
        public string PC_VIEW_COLUMN { get; set; }
        public string PC_VIEW_NAME { get; set; }
        public bool INQUIRY { get; set; }
        public bool APPLICANT { get; set; }
        public bool STUDENTS { get; set; }
        public bool STATUS { get; set; }
        public int RECORD_NUMBER { get; set; }
        public string PC_VIEW_SORT_COL { get; set; }
        public string SORT_ORDER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ACADEMIC_SESSION { get; set; }
    }
}
