//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFINTEGRATION
    {
        public int RECORD_ID { get; set; }
        public string SSN { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string PC_TABLE_NAME { get; set; }
        public string PROCESS_STATUS { get; set; }
        public System.DateTime PROCESS_DATE_TIME { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public int ProfileId { get; set; }
        public int RunId { get; set; }
    
        public virtual PFISETTING PFISETTING { get; set; }
    }
}
