//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFIntegrationLog
    {
        public int PFIntegrationLogId { get; set; }
        public int ProfileId { get; set; }
        public int RunId { get; set; }
        public System.DateTime StartDatetime { get; set; }
        public Nullable<System.DateTime> EndDatetime { get; set; }
        public Nullable<int> ProcessedRecords { get; set; }
        public Nullable<int> LoggedErrors { get; set; }
    
        public virtual PFISETTING PFISETTING { get; set; }
    }
}
