//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PFISETTING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PFISETTING()
        {
            this.PFIERRORLOGs = new HashSet<PFIERRORLOG>();
            this.PFINTEGRATIONs = new HashSet<PFINTEGRATION>();
            this.PFIntegrationLogs = new HashSet<PFIntegrationLog>();
            this.PFITABLES = new HashSet<PFITABLE>();
        }
    
        public int PROFILE_ID { get; set; }
        public string PROFILE_NAME { get; set; }
        public bool INQUIRY { get; set; }
        public bool APPLICANT { get; set; }
        public bool STUDENT { get; set; }
        public string INTERVAL { get; set; }
        public int INTERVAL_NUMBER { get; set; }
        public Nullable<System.DateTime> LAST_START { get; set; }
        public Nullable<System.DateTime> LAST_STOP { get; set; }
        public string POWERCAMPUS_DSN { get; set; }
        public string POWERFAIDS_DSN { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public System.Guid Guid { get; set; }
        public bool IsActive { get; set; }
        public bool IsOnce { get; set; }
        public bool IsProcessAll { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PFIERRORLOG> PFIERRORLOGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PFINTEGRATION> PFINTEGRATIONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PFIntegrationLog> PFIntegrationLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PFITABLE> PFITABLES { get; set; }
    }
}
