//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLEDGESCHEDULEWP
    {
        public string USER_ID { get; set; }
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public int PLEDGE_NUMBER { get; set; }
        public int PAYMENT_SEQUENCE { get; set; }
        public decimal PAST_DUE_AMOUNT { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public decimal DUE_AMOUNT { get; set; }
        public string REMINDER_FLAG { get; set; }
        public string GIFT_ALLOCATION { get; set; }
        public string GIFT_FORM { get; set; }
        public string GIFT_PROGRAM { get; set; }
        public string GIFT_TYPE { get; set; }
        public string GIFT_CAMPAIGN { get; set; }
        public string GIFT_APPEAL { get; set; }
        public string GIFT_TEST { get; set; }
        public string PROJECT_ID { get; set; }
        public int ROWNUM { get; set; }
    }
}
