//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLEDGESCHEDULE
    {
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public int PLEDGE_NUMBER { get; set; }
        public int PAYMENT_SEQUENCE { get; set; }
        public System.DateTime PAYMENT_DUE_DATE { get; set; }
        public decimal PAYMENT_DUE_AMOUNT { get; set; }
        public decimal PAYMENT_BALANCE_AMT { get; set; }
        public decimal PAYMENT_PAID_AMT { get; set; }
        public Nullable<System.DateTime> LAST_PAYMENT_DATE { get; set; }
        public string REMINDER_FLAG { get; set; }
        public int REMINDER_COUNTER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
