//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTALACCOUNT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PORTALACCOUNT()
        {
            this.PORTALIQSESSIONs = new HashSet<PORTALIQSESSION>();
        }
    
        public int PORTALACCOUNT_ID { get; set; }
        public string ACCOUNT_ID { get; set; }
        public string LOGIN_ID { get; set; }
        public string NETWORKLOGIN_ID { get; set; }
        public string AD_DOMAIN_NAME { get; set; }
        public string AD_CONTAINER_PATH { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        public virtual ABT_ACCOUNTS ABT_ACCOUNTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PORTALIQSESSION> PORTALIQSESSIONs { get; set; }
    }
}
