//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTALLOGINLOCKOUT
    {
        public int PORTALLOGINLOCKOUT_ID { get; set; }
        public string ACCOUNT_ID { get; set; }
        public string LOGIN_ID { get; set; }
        public string REQUEST_IP_ADDR { get; set; }
        public short AD_LOGIN_ATTEMPTS { get; set; }
        public string AD_LOGIN_LOCKOUT { get; set; }
        public string AUTO_AUTH { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
