//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PORTALADLOGONNAME
    {
        public int PORTALADLOGONNAME_ID { get; set; }
        public string COLUMN_NAME { get; set; }
        public string DISPLAY_NAME { get; set; }
        public short COLUMN_SIZE { get; set; }
        public string USE_ALL_CHARS { get; set; }
        public short USE_FIRST_CHARS { get; set; }
        public short USE_LAST_CHARS { get; set; }
        public short CONCAT_ORDER { get; set; }
        public string ACTIVE { get; set; }
        public string DEFAULT_VALUE { get; set; }
        public string SEPARATOR { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
