//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramOfStudy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProgramOfStudy()
        {
            this.ApplicationPrograms = new HashSet<ApplicationProgram>();
            this.ApplicationProgramSettings = new HashSet<ApplicationProgramSetting>();
            this.InquiryPrograms = new HashSet<InquiryProgram>();
            this.InquiryProgramSettings = new HashSet<InquiryProgramSetting>();
        }
    
        public int ProgramOfStudyId { get; set; }
        public int Program { get; set; }
        public int Degree { get; set; }
        public int Curriculum { get; set; }
        public int PopulationId { get; set; }
        public string PictureDirectory { get; set; }
        public string PictureName { get; set; }
        public string PictureExtension { get; set; }
        public Nullable<int> CampusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationProgram> ApplicationPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationProgramSetting> ApplicationProgramSettings { get; set; }
        public virtual CODE_PICTUREDIR CODE_PICTUREDIR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryProgram> InquiryPrograms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InquiryProgramSetting> InquiryProgramSettings { get; set; }
    }
}
