//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROSPECTRATING
    {
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public string RATING_TYPE { get; set; }
        public System.DateTime RATING_DATE { get; set; }
        public string RATING_RESULT { get; set; }
        public string SCREENING_CODE { get; set; }
        public string SCREENING_ID { get; set; }
        public Nullable<System.DateTime> SCREENING_DATE { get; set; }
        public string SCREENING_METHOD { get; set; }
        public string GIVING_PROBABILITY { get; set; }
        public string RESOURCE_ALLOCATION { get; set; }
        public string FUNDING_INTEREST { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
