//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RELATIONSHIP
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string RELATION_CODE_ID { get; set; }
        public string RELATION_TYPE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public int RECORD_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> BIRTH_DATE { get; set; }
        public string DECEASED_FLAG { get; set; }
        public Nullable<System.DateTime> DECEASED_DATE { get; set; }
        public string TERMINATE_REASON { get; set; }
        public bool AttendedInstitution { get; set; }
        public Nullable<bool> isrespfinancial { get; set; }
        public string Profession { get; set; }
        public string MobileNumber { get; set; }
        public string AddressSame { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string PostalCode { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<int> UniversityId { get; set; }
        public string Email { get; set; }
        public string OtherRegion { get; set; }
        public Nullable<bool> isGuardian { get; set; }
        public string SiblingIDNumber { get; set; }
        public string CompanyName { get; set; }
        public string TKHEmployeeId { get; set; }
    }
}
