//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class REPEATVALUE
    {
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string REPEAT_TYPE { get; set; }
        public string CNT_HIGHEST_GRADE { get; set; }
        public string CUM_CNT_ATTEMPTED { get; set; }
        public string CUM_CNT_EARNED { get; set; }
        public string CUM_CNT_TOTAL { get; set; }
        public string CUM_CNT_TRANSFER { get; set; }
        public string CUM_CNT_GPA { get; set; }
        public string CUM_CNT_CONTACT_HR { get; set; }
        public string SES_CNT_ATTEMPTED { get; set; }
        public string SES_CNT_EARNED { get; set; }
        public string SES_CNT_TOTAL { get; set; }
        public string SES_CNT_TRANSFER { get; set; }
        public string SES_CNT_GPA { get; set; }
        public string SES_CNT_CONTACT_HR { get; set; }
        public string RM_PREV_ATTEMPTED { get; set; }
        public string RM_PREV_EARNED { get; set; }
        public string RM_PREV_TOTAL { get; set; }
        public string RM_PREV_TRANSFER { get; set; }
        public string RM_PREV_GPA { get; set; }
        public string RM_PREV_CONTACT_HR { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
    }
}
