//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reported1098TInformationDetail
    {
        public int ReportedInformationDetailId { get; set; }
        public int ReportedInformationId { get; set; }
        public string TaxYear { get; set; }
        public string PeopleCodeId { get; set; }
        public decimal PreviousTuitionReported { get; set; }
        public decimal PreviousPaymentsReported { get; set; }
        public decimal CurrentTuitionBilled { get; set; }
        public decimal PrevChargesDecrement { get; set; }
        public decimal CurrentPayments { get; set; }
        public decimal PrevPaymentDecrement { get; set; }
        public decimal PaymentAdjustments { get; set; }
        public decimal CurrentScholarships { get; set; }
        public decimal ScholarshipAdjustments { get; set; }
        public decimal QTRECap { get; set; }
        public decimal Box1Amount { get; set; }
        public decimal CumulativeTuitionBilled { get; set; }
        public decimal CumulativePaymentsReported { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Reported1098TInformation Reported1098TInformation { get; set; }
    }
}
