//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reported1098TPeriodSummary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reported1098TPeriodSummary()
        {
            this.Reported1098TSummaryDetail = new HashSet<Reported1098TSummaryDetail>();
        }
    
        public int ReportedPeriodSummaryId { get; set; }
        public int ReportedInformationId { get; set; }
        public string TaxYear { get; set; }
        public string PeopleCodeId { get; set; }
        public string AcademicYear { get; set; }
        public string AcademicTerm { get; set; }
        public System.DateTime AcaTermStartDate { get; set; }
        public System.DateTime AcaTermEndDate { get; set; }
        public decimal CurrentChargesBilled { get; set; }
        public decimal TuitionRefund { get; set; }
        public decimal CurrentPaymentAmount { get; set; }
        public decimal PaymentRefund { get; set; }
        public decimal CurrentNetPaymentAmount { get; set; }
        public decimal PriorRptPaymentAdjustment { get; set; }
        public decimal PriorRptTuitionAdjustment { get; set; }
        public decimal QTRECap { get; set; }
        public decimal TotalScholarshipAmount { get; set; }
        public decimal ScholarshipAdjustment { get; set; }
        public bool IncludeNextYearAmount { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Reported1098TInformation Reported1098TInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reported1098TSummaryDetail> Reported1098TSummaryDetail { get; set; }
    }
}
