//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ROOM
    {
        public string ORG_CODE { get; set; }
        public string ORG_ID { get; set; }
        public string ORG_CODE_ID { get; set; }
        public string BUILDING_CODE { get; set; }
        public string ROOM_ID { get; set; }
        public string ROOM_NAME { get; set; }
        public string ROOM_TYPE { get; set; }
        public Nullable<System.DateTime> RENOVATE_DATE { get; set; }
        public string ROOM_CONDITION { get; set; }
        public string POWER { get; set; }
        public string LIGHTING { get; set; }
        public string AIR_CONDITIONING { get; set; }
        public Nullable<int> TOTAL_SQUARE_FT { get; set; }
        public Nullable<int> NUMBER_WINDOWS { get; set; }
        public Nullable<int> MIN_OCCUPANCY { get; set; }
        public Nullable<int> MAX_OCCUPANCY { get; set; }
        public string SEAT_TYPE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string FAX_NUMBER { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string ALLOW_SCHEDULING { get; set; }
        public string FLOOR_ID { get; set; }
    }
}
