//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALUTATION
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string SALUTATION_TYPE { get; set; }
        public string SALUTATION1 { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string INCLUDE_PREFIX { get; set; }
        public string INCLUDE_FIRST_NAME { get; set; }
        public string INCLUDE_MIDDLE_NAME { get; set; }
        public string INCLUDE_LAST_NAME { get; set; }
        public string INCLUDE_SUFFIX { get; set; }
        public string INCLUDE_NICKNAME { get; set; }
        public string Include_LastNamePrefix { get; set; }
    }
}
