//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Save_PFISETTINGS
    {
        public int PROFILE_ID { get; set; }
        public string PROFILE_NAME { get; set; }
        public bool INQUIRY { get; set; }
        public bool APPLICANT { get; set; }
        public bool STUDENT { get; set; }
        public string INTERVAL { get; set; }
        public int INTERVAL_NUMBER { get; set; }
        public Nullable<System.DateTime> LAST_START { get; set; }
        public Nullable<System.DateTime> LAST_STOP { get; set; }
        public string POWERCAMPUS_DSN { get; set; }
        public string POWERFAIDS_DSN { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
