//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedApplication
    {
        public int SavedApplicationId { get; set; }
        public System.Guid Token { get; set; }
        public Nullable<int> PersonId { get; set; }
        public string Email { get; set; }
        public int ApplicationFormSettingId { get; set; }
        public int FormLayoutId { get; set; }
        public string JsonDetail { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
    
        public virtual ApplicationFormSetting ApplicationFormSetting { get; set; }
        public virtual FormLayout FormLayout { get; set; }
    }
}
