//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarshipOffering
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScholarshipOffering()
        {
            this.ScholarshipApplications = new HashSet<ScholarshipApplication>();
            this.ScholarshipApplicationCopies = new HashSet<ScholarshipApplicationCopy>();
            this.ScholarshipOfferingLevels = new HashSet<ScholarshipOfferingLevel>();
            this.ScholarshipOfferingReqs = new HashSet<ScholarshipOfferingReq>();
        }
    
        public int ScholarshipOfferingId { get; set; }
        public string ScholarshipType { get; set; }
        public string ScholarshipGroup { get; set; }
        public string Name { get; set; }
        public Nullable<int> TermPeriodId { get; set; }
        public Nullable<int> SessionPeriodId { get; set; }
        public short Priority { get; set; }
        public string IsExclusive { get; set; }
        public Nullable<int> DisbursementPolicyId { get; set; }
        public byte DisbursementType { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string Description { get; set; }
    
        public virtual CODE_SCHOLARSHIPTYPE CODE_SCHOLARSHIPTYPE { get; set; }
        public virtual DisbursementPolicy DisbursementPolicy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipApplication> ScholarshipApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipApplicationCopy> ScholarshipApplicationCopies { get; set; }
        public virtual TermPeriod TermPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipOfferingLevel> ScholarshipOfferingLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipOfferingReq> ScholarshipOfferingReqs { get; set; }
    }
}
