//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScholarshipOfferingLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScholarshipOfferingLevel()
        {
            this.ScholarshipApplications = new HashSet<ScholarshipApplication>();
        }
    
        public int ScholarshipOfferingLevelId { get; set; }
        public int ScholarshipOfferingId { get; set; }
        public string ScholarshipLevel { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        public Nullable<decimal> MaxAmount { get; set; }
        public Nullable<decimal> EstimatedAmountPerPerson { get; set; }
        public Nullable<short> NumScholarshipAvailable { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        public virtual CODE_SCHOLARSHIPLEVEL CODE_SCHOLARSHIPLEVEL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipApplication> ScholarshipApplications { get; set; }
        public virtual ScholarshipOffering ScholarshipOffering { get; set; }
    }
}
