//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTIONPREREQUISITE
    {
        public int PREREQ_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string EVENT_ID { get; set; }
        public string EVENT_SUB_TYPE { get; set; }
        public string SECTION { get; set; }
        public int SEQUENCE_NUMBER { get; set; }
        public string PREREQ_TYPE { get; set; }
        public string OPEN_PARENS { get; set; }
        public string CLOSE_PARENS { get; set; }
        public string LOGICAL_OPERATOR { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        public virtual SECTIONPREREQCOURSE SECTIONPREREQCOURSE { get; set; }
        public virtual SECTIONPREREQPERMISSION SECTIONPREREQPERMISSION { get; set; }
        public virtual SECTIONPREREQTESTSCORE SECTIONPREREQTESTSCORE { get; set; }
    }
}
