//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTIONGRADINGTASK
    {
        public int SECTIONGRADINGTASKS_KEY { get; set; }
        public int SECTIONGRADINGDETAIL_KEY { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public int SORT_ORDER { get; set; }
        public Nullable<decimal> TOTAL_GRADE_POINTS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
