//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SECTION
    {
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string EVENT_ID { get; set; }
        public string EVENT_SUB_TYPE { get; set; }
        public string SECTION1 { get; set; }
        public string EVENT_MED_NAME { get; set; }
        public string EVENT_LONG_NAME { get; set; }
        public string EVENT_TYPE { get; set; }
        public string ORG_CODE_ID { get; set; }
        public string PROGRAM { get; set; }
        public string COLLEGE { get; set; }
        public string DEPARTMENT { get; set; }
        public string CURRICULUM { get; set; }
        public string CLASS_LEVEL { get; set; }
        public string NONTRAD_PROGRAM { get; set; }
        public string POPULATION { get; set; }
        public string EVENT_STATUS { get; set; }
        public string CIP_CODE { get; set; }
        public string SPEEDE_CODE { get; set; }
        public string SERIAL_ID { get; set; }
        public string ROOM_TYPE { get; set; }
        public string CREDIT_TYPE { get; set; }
        public decimal CREDITS { get; set; }
        public decimal CEU { get; set; }
        public decimal MINUTES_WEEK { get; set; }
        public decimal CONTACT_HOURS { get; set; }
        public string REPORT_CARD_PRINT { get; set; }
        public string TRANSCRIPT_PRINT { get; set; }
        public int MIN_PARTICIPANT { get; set; }
        public int TARGET_PARTICIPANT { get; set; }
        public int MAX_PARTICIPANT { get; set; }
        public string OTHER_ORG { get; set; }
        public int OTHER_ORG_PART { get; set; }
        public string OTHER_PROGRAM { get; set; }
        public int OTHER_PROGRAM_PART { get; set; }
        public string OTHER_COLLEGE { get; set; }
        public int OTHER_COLLEGE_PART { get; set; }
        public string OTHER_DEPARTMENT { get; set; }
        public int OTHER_DEPT_PART { get; set; }
        public string OTHER_CURRICULUM { get; set; }
        public int OTHER_CURRIC_PART { get; set; }
        public string OTHER_CLASS_LEVEL { get; set; }
        public int OTHER_CLEVEL_PART { get; set; }
        public string OTHER_NONTRAD { get; set; }
        public int OTHER_NONTRAD_PART { get; set; }
        public string OTHER_POPULATION { get; set; }
        public int OTHER_POP_PART { get; set; }
        public int ADDS { get; set; }
        public int DROPS { get; set; }
        public int WAIT_LIST { get; set; }
        public int OTHER_ORG_ADD { get; set; }
        public int OTHER_ORG_DROP { get; set; }
        public int OTHER_ORG_WAIT { get; set; }
        public int OTHER_PROGRAM_ADD { get; set; }
        public int OTHER_PROGRAM_DROP { get; set; }
        public int OTHER_PROGRAM_WAIT { get; set; }
        public int OTHER_COLLEGE_ADD { get; set; }
        public int OTHER_COLLEGE_DROP { get; set; }
        public int OTHER_COLLEGE_WAIT { get; set; }
        public int OTHER_DEPT_ADD { get; set; }
        public int OTHER_DEPT_DROP { get; set; }
        public int OTHER_DEPT_WAIT { get; set; }
        public int OTHER_CURR_ADD { get; set; }
        public int OTHER_CURR_DROP { get; set; }
        public int OTHER_CURR_WAIT { get; set; }
        public int OTHER_CLEVEL_ADD { get; set; }
        public int OTHER_CLEVEL_DROP { get; set; }
        public int OTHER_CLEVEL_WAIT { get; set; }
        public int OTHER_NONTRAD_ADD { get; set; }
        public int OTHER_NONTRAD_DROP { get; set; }
        public int OTHER_NONTRAD_WAIT { get; set; }
        public int OTHER_POP_ADD { get; set; }
        public int OTHER_POP_DROP { get; set; }
        public int OTHER_POP_WAIT { get; set; }
        public string WEEK_NUMBER { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string DESCRIPTION { get; set; }
        public string SEC_ENROLL_STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string GENERAL_ED { get; set; }
        public decimal CONTACT_HR_SESSION { get; set; }
        public string MID_GRD_RECEIVED { get; set; }
        public string FINAL_GRD_RECEIVED { get; set; }
        public string SCHEDULE_PRIORITY { get; set; }
        public string PUBLICATION_NAME_1 { get; set; }
        public string PUBLICATION_NAME_2 { get; set; }
        public Nullable<System.DateTime> LATE_REG_FEE_DATE { get; set; }
        public int REQUESTED_MEETINGS { get; set; }
        public int SCHEDULED_MEETINGS { get; set; }
        public string ANONYMOUS_GRADING { get; set; }
        public string CANCEL_REASON { get; set; }
        public Nullable<System.DateTime> LAST_REFUND_DATE { get; set; }
        public Nullable<int> ADJUSTMENT_POLICY_ID { get; set; }
        public string REPEATABLE { get; set; }
        public string ACTIVITY_TYPE_GRADING { get; set; }
        public string REGISTRATION_TYPE { get; set; }
        public int SectionId { get; set; }
        public byte AssignmentWeightingMethod { get; set; }
        public Nullable<bool> UseWeightedAssignmentTypes { get; set; }
        public bool RequiresGradeApproval { get; set; }
        public bool HideOnlineSearch { get; set; }
    }
}
