//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionPeriodFilter
    {
        public int SessionPeriodFilterId { get; set; }
        public byte UIAreaId { get; set; }
        public int SessionPeriodId { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual UIArea UIArea { get; set; }
    }
}
