//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEVISBATCHHEADER
    {
        public int BATCH_NUMBER { get; set; }
        public string SCHOOL_CODE { get; set; }
        public string SEVIS_USER { get; set; }
        public string BATCH_TYPE { get; set; }
        public string STATUS { get; set; }
        public System.DateTime BATCH_DATE { get; set; }
        public Nullable<System.DateTime> BATCH_SENT { get; set; }
        public Nullable<System.DateTime> BATCH_RECEIVED { get; set; }
        public string ERROR_CODE { get; set; }
        public string ERROR_MSG { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
