//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Signer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Signer()
        {
            this.ElectronicDegreeInstSigners = new HashSet<ElectronicDegreeInstSigner>();
        }
    
        public int SignerId { get; set; }
        public string Name { get; set; }
        public string FirstSurname { get; set; }
        public string SecondSurname { get; set; }
        public string Curp { get; set; }
        public int SignerPositionId { get; set; }
        public int AbreviationTitleId { get; set; }
        public string Thumbprint { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string CreateUserName { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public string RevisionUserName { get; set; }
    
        public virtual ABT_USERS ABT_USERS { get; set; }
        public virtual CODE_ABREVIATIONTITLE CODE_ABREVIATIONTITLE { get; set; }
        public virtual CODE_SIGNERPOSITION CODE_SIGNERPOSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectronicDegreeInstSigner> ElectronicDegreeInstSigners { get; set; }
    }
}
