//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMapOptionDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteMapOptionDetail()
        {
            this.SiteMapOptionDetailRoles = new HashSet<SiteMapOptionDetailRole>();
        }
    
        public int SiteMapOptionDetailId { get; set; }
        public int SiteMapOptionId { get; set; }
        public string LinkId { get; set; }
        public Nullable<int> NameFormatCategoryId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string ExternalLink { get; set; }
        public bool IsCustom { get; set; }
    
        public virtual NameFormatCategory NameFormatCategory { get; set; }
        public virtual SiteMapOption SiteMapOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteMapOptionDetailRole> SiteMapOptionDetailRoles { get; set; }
    }
}
