//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteMapOption
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SiteMapOption()
        {
            this.SiteMapOptionDetails = new HashSet<SiteMapOptionDetail>();
            this.SiteMapOptionRoles = new HashSet<SiteMapOptionRole>();
        }
    
        public int SiteMapOptionId { get; set; }
        public string LinkId { get; set; }
        public Nullable<int> NameFormatCategoryId { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string ExternalLink { get; set; }
        public bool IsCustom { get; set; }
    
        public virtual NameFormatCategory NameFormatCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteMapOptionDetail> SiteMapOptionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiteMapOptionRole> SiteMapOptionRoles { get; set; }
    }
}
