//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPOUSE
    {
        public int RECORD_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public Nullable<int> RELATION_RECORD_ID { get; set; }
        public string RESIDES_TOGETHER { get; set; }
        public Nullable<System.DateTime> MARRIAGE_DATE { get; set; }
        public string SEPARATED_FLAG { get; set; }
        public Nullable<System.DateTime> SEPARATED_DATE { get; set; }
        public string DIVORCED_FLAG { get; set; }
        public Nullable<System.DateTime> DIVORCED_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
