//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATEMENTHEADER
    {
        public int STATEMENT_NUMBER { get; set; }
        public string PEOPLE_ORG_CODE_ID { get; set; }
        public string PEOPLE_ORG_CODE { get; set; }
        public string PEOPLE_ORG_ID { get; set; }
        public string MAILING_TYPE { get; set; }
        public string ADDRESS_TYPE { get; set; }
        public string MEDIUM_TYPE { get; set; }
        public decimal PREVIOUS_BALANCE { get; set; }
        public decimal TOTAL_CHARGES { get; set; }
        public decimal TOTAL_CREDITS { get; set; }
        public decimal TOTAL_ANTICIPATED { get; set; }
        public decimal CURRENT_BALANCE { get; set; }
        public string GENERAL_MESSAGE { get; set; }
        public string PRIMARY_FLAG { get; set; }
        public string STATEMENT_TYPE { get; set; }
        public string STATEMENT_TITLE { get; set; }
        public System.DateTime STATEMENT_DATE { get; set; }
        public System.DateTime DUE_DATE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string CLASS_LEVEL { get; set; }
        public string ENROLL_SEPARATION { get; set; }
        public string PREFIX { get; set; }
        public string FIRST_NAME { get; set; }
        public string MIDDLE_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string SUFFIX { get; set; }
        public string ADDRESS_LINE_1 { get; set; }
        public string ADDRESS_LINE_2 { get; set; }
        public string ADDRESS_LINE_3 { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIP_CODE { get; set; }
        public string COUNTRY { get; set; }
        public string CITY_PREFIX { get; set; }
        public string CITY_SUFFIX { get; set; }
        public string BATCH { get; set; }
        public string PRINT_ONLY_NEW { get; set; }
        public string EXTERNAL_FLAG { get; set; }
        public string ORG_NAME { get; set; }
        public string ORG_ADDRESS_LINE_1 { get; set; }
        public string ORG_ADDRESS_LINE_2 { get; set; }
        public string ORG_ADDRESS_LINE_3 { get; set; }
        public string ORG_CITY { get; set; }
        public string ORG_STATE { get; set; }
        public string ORG_ZIP_CODE { get; set; }
        public string ORG_COUNTRY { get; set; }
        public string ORG_CITY_PREFIX { get; set; }
        public string ORG_CITY_SUFFIX { get; set; }
        public string STATEMENT_OPTION { get; set; }
        public string PAYMENT_COUPON_FLG { get; set; }
        public string POS_NEG_MESSAGE { get; set; }
        public string ANTICIPATED_MSG { get; set; }
        public string ADDRESS_ORG_NAME_1 { get; set; }
        public string ADDRESS_ORG_NAME_2 { get; set; }
        public string STATEMENT_DESC { get; set; }
        public string MAIL_TO_REC_LINE_1 { get; set; }
        public string MAIL_TO_REC_LINE_2 { get; set; }
        public string MAIL_TO_ADD_LINE_1 { get; set; }
        public string MAIL_TO_ADD_LINE_2 { get; set; }
        public string MAIL_TO_ADD_LINE_3 { get; set; }
        public string MAIL_TO_CITY { get; set; }
        public string MAIL_TO_STATE { get; set; }
        public string MAIL_TO_ZIP_CODE { get; set; }
        public string MAIL_TO_COUNTRY { get; set; }
        public string MAIL_TO_CITY_PREFIX { get; set; }
        public string MAIL_TO_CITY_SUFFIX { get; set; }
        public Nullable<decimal> PAYPLAN_BALANCE { get; set; }
        public Nullable<decimal> PAYMENT_DUE { get; set; }
        public string PAYPLAN_FLAG { get; set; }
        public string CREDITCARD_TYPES { get; set; }
        public decimal PAYMENT_OPTION_OTHERCHARGES { get; set; }
        public decimal PAYMENT_OPTION_INSTALLMENT { get; set; }
        public Nullable<int> STATEMENTS_REMAINING { get; set; }
        public string STATEMENT { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public decimal PAYPLAN_OTHERCHARGES { get; set; }
        public decimal PAYPLAN_INSTALLMENT { get; set; }
        public string LastNamePrefix { get; set; }
        public string ADDRESS_LINE_4 { get; set; }
        public string HOUSE_NUMBER { get; set; }
        public string ORG_ADDRESS_LINE_4 { get; set; }
        public string ORG_HOUSE_NUMBER { get; set; }
        public string MAIL_TO_ADD_LINE_4 { get; set; }
        public string MAIL_TO_HOUSE_NUMBER { get; set; }
    }
}
