//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATEMENTLINE
    {
        public int STATEMENT_NUMBER { get; set; }
        public int STATEMENT_LINE { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string CHARGE_CREDIT_TYPE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<System.DateTime> ENTRY_DATE { get; set; }
        public Nullable<int> RECEIPT_NUMBER { get; set; }
        public string PAYMENT_PLAN_ID { get; set; }
        public Nullable<decimal> SCHED_PAYMENT_AMT { get; set; }
        public Nullable<decimal> LATE_AMOUNT { get; set; }
        public Nullable<decimal> TOTAL_DUE_AMOUNT { get; set; }
        public string STATEMENT_MESSAGE { get; set; }
        public string EVENT_ID { get; set; }
        public string EVENT_SUB_TYPE { get; set; }
        public string SECTION { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string EVENT_NAME { get; set; }
        public Nullable<decimal> CEU { get; set; }
        public Nullable<decimal> CREDIT_GRADE { get; set; }
        public string DAY { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public Nullable<System.DateTime> END_TIME { get; set; }
        public string ORG_CODE_ID { get; set; }
        public string BUILDING_CODE { get; set; }
        public string ROOM_ID { get; set; }
        public string PERSON_CODE_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string LINE_TYPE { get; set; }
        public string PEOPLE_ORIGIN_NAME { get; set; }
        public string ORG_ORIGIN_NAME { get; set; }
        public string ANTICIPATED_FLAG { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string SUMMARY_DETAIL_FLAG { get; set; }
        public string PRINT_ORDER { get; set; }
        public string CASH_RECEIPT_NOTE { get; set; }
        public Nullable<int> CHARGECREDITNUMBER { get; set; }
        public string PAYMENT_OPTION { get; set; }
        public string PAYPLAN_ELIGIBLE { get; set; }
    }
}
