//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class STDDEGREQEVENT
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string MATRIC_YEAR { get; set; }
        public string MATRIC_TERM { get; set; }
        public string RECORD_TYPE { get; set; }
        public string PROGRAM { get; set; }
        public string DEGREE { get; set; }
        public string CURRICULUM { get; set; }
        public string DISCIPLINE { get; set; }
        public string EVENT_CLASS { get; set; }
        public string EVENT_ID { get; set; }
        public string EVENT_SUB_TYPE { get; set; }
        public string EVENT_NAME { get; set; }
        public string ENROLLED_SEQ { get; set; }
        public string REQUIRED { get; set; }
        public string ANY_PASSING_GRADE { get; set; }
        public string MIN_GRADE { get; set; }
        public string WILDCARD_ROW { get; set; }
        public string CUSTOMIZED { get; set; }
        public string TAKEN_YEAR { get; set; }
        public string TAKEN_TERM { get; set; }
        public string TAKEN_SESSION { get; set; }
        public string TAKEN_EVENT_ID { get; set; }
        public string TAKEN_SUB_TYPE { get; set; }
        public string TAKEN_SECTION { get; set; }
        public string STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string NOTES { get; set; }
        public string FROM_WILDCARD_ROW { get; set; }
        public string INCLUDE_DEGREE_GPA { get; set; }
        public decimal SEQUENCE_NUMBER { get; set; }
        public string OPEN_PARENS { get; set; }
        public string CLOSE_PARENS { get; set; }
        public string LOGICAL_OPERATOR { get; set; }
        public string INCLUDE_CREDITS { get; set; }
    }
}
