//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentProxy
    {
        public int StudentProxyId { get; set; }
        public int StudentId { get; set; }
        public int ProxyId { get; set; }
        public bool CanViewAcaPlan { get; set; }
        public bool CanViewSchedule { get; set; }
        public bool CanViewBalance { get; set; }
        public bool CanViewFinAid { get; set; }
        public bool CanMakePayment { get; set; }
        public bool CanViewTranscript { get; set; }
        public bool CanViewGradeReport { get; set; }
        public bool CanViewStopList { get; set; }
        public bool CanViewAddress { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public bool CanViewAssignmentGradeReport { get; set; }
    }
}
