//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class STUDENTFINANCIAL
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string PAYMENT_PLAN { get; set; }
        public string TUITION_PLAN { get; set; }
        public string TUITION_EXEMPTION { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string ECONOMIC_RATING { get; set; }
        public string COUNTY { get; set; }
        public string COUNTY_RES_MONTHS { get; set; }
        public Nullable<System.DateTime> COUNTY_VER_DATE { get; set; }
        public string PREVIOUS_COUNTY { get; set; }
        public string PREV_CNTY_RES_MTH { get; set; }
        public Nullable<System.DateTime> PREV_CNTY_VER_DATE { get; set; }
        public string STATE { get; set; }
        public string STATE_RES_MONTHS { get; set; }
        public Nullable<System.DateTime> STATE_VER_DATE { get; set; }
        public string PREVIOUS_STATE { get; set; }
        public string PREV_STATE_RES_MTH { get; set; }
        public Nullable<System.DateTime> PREV_STATE_VER_DATE { get; set; }
        public decimal CREDIT_BILLING { get; set; }
        public string LAST_ACTIVITY { get; set; }
        public string CURRENT_ACTIVITY { get; set; }
        public string PAYMENT_OPTION { get; set; }
        public decimal CREDIT_BILLING_TERM { get; set; }
    }
}
