//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxProfile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxProfile()
        {
            this.CODE_CHARGECREDIT = new HashSet<CODE_CHARGECREDIT>();
            this.TaxProfileValidities = new HashSet<TaxProfileValidity>();
        }
    
        public int TaxProfileId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Create_Time { get; set; }
        public string Create_Opid { get; set; }
        public string Create_Terminal { get; set; }
        public System.DateTime Revision_Date { get; set; }
        public System.DateTime Revision_Time { get; set; }
        public string Revision_Opid { get; set; }
        public string Revision_Terminal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CODE_CHARGECREDIT> CODE_CHARGECREDIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxProfileValidity> TaxProfileValidities { get; set; }
    }
}
