//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxProfileValidity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxProfileValidity()
        {
            this.ChargeCreditTaxes = new HashSet<ChargeCreditTax>();
            this.TaxProfileDetails = new HashSet<TaxProfileDetail>();
        }
    
        public int TaxProfileValidityId { get; set; }
        public int TaxProfileId { get; set; }
        public System.DateTime StartDatetime { get; set; }
        public Nullable<System.DateTime> EndDatetime { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Create_Time { get; set; }
        public string Create_Opid { get; set; }
        public string Create_Terminal { get; set; }
        public System.DateTime Revision_Date { get; set; }
        public System.DateTime Revision_Time { get; set; }
        public string Revision_Opid { get; set; }
        public string Revision_Terminal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChargeCreditTax> ChargeCreditTaxes { get; set; }
        public virtual TaxProfile TaxProfile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxProfileDetail> TaxProfileDetails { get; set; }
    }
}
