//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxProfileDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxProfileDetail()
        {
            this.FiscalRecordTaxMappings = new HashSet<FiscalRecordTaxMapping>();
        }
    
        public int TaxProfileDetailId { get; set; }
        public int TaxProfileValidityId { get; set; }
        public int ChargeCreditCodeId { get; set; }
        public decimal Percentage { get; set; }
        public byte Sequence { get; set; }
        public byte CalculatedOver { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Create_Time { get; set; }
        public string Create_Opid { get; set; }
        public string Create_Terminal { get; set; }
        public System.DateTime Revision_Date { get; set; }
        public System.DateTime Revision_Time { get; set; }
        public string Revision_Opid { get; set; }
        public string Revision_Terminal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiscalRecordTaxMapping> FiscalRecordTaxMappings { get; set; }
        public virtual TaxProfileValidity TaxProfileValidity { get; set; }
    }
}
