//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TESTSCORE
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string TEST_ID { get; set; }
        public string TEST_TYPE { get; set; }
        public System.DateTime TEST_DATE { get; set; }
        public decimal RAW_SCORE { get; set; }
        public decimal CONVERSION_FACTOR { get; set; }
        public decimal CONVERTED_SCORE { get; set; }
        public string TRANSCRIPT_PRINT { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string ALPHA_SCORE { get; set; }
        public string ALPHA_SCORE_1 { get; set; }
        public string ALPHA_SCORE_2 { get; set; }
        public string ALPHA_SCORE_3 { get; set; }
    }
}
