//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranscriptRequestTransaction
    {
        public int TranscriptRequestTransactionId { get; set; }
        public int PaymentTransactionId { get; set; }
        public int PersonId { get; set; }
        public System.DateTime RequestDate { get; set; }
        public int RequestCopies { get; set; }
        public string MailToName { get; set; }
        public string MailToAddress1 { get; set; }
        public string MailToAddress2 { get; set; }
        public string MailToAddress3 { get; set; }
        public string MailToCity { get; set; }
        public Nullable<int> MailToStateId { get; set; }
        public string MailToZip { get; set; }
        public int MailToCountryId { get; set; }
        public int FeeCodeId { get; set; }
        public decimal FeeAmount { get; set; }
        public string Reason { get; set; }
        public bool IsDisclosureAccepted { get; set; }
        public bool IsOnlineRequest { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public string MailToAddress4 { get; set; }
        public string MailToHouseNumber { get; set; }
    
        public virtual PaymentTransaction PaymentTransaction { get; set; }
    }
}
