//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSCOMPETENCY
    {
        public int TRANSCOMP_ID { get; set; }
        public int COMPETENCY_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public int GROUP_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public string CATEGORY { get; set; }
        public string SUMMARY_REFERENCE { get; set; }
        public string COMPLETED { get; set; }
        public string COMPLETED_YEAR { get; set; }
        public string COMPLETED_TERM { get; set; }
        public string COMPLETED_SESSION { get; set; }
        public string COMPLETED_EVENT_ID { get; set; }
        public string COMPLETED_SUB_TYPE { get; set; }
        public string COMPLETED_SECTION { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
