//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSCRIPTGPA
    {
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string TRANSCRIPT_SEQ { get; set; }
        public string RECORD_TYPE { get; set; }
        public string PROGRAM { get; set; }
        public string DEGREE { get; set; }
        public string CURRICULUM { get; set; }
        public decimal ATTEMPTED_CREDITS { get; set; }
        public decimal EARNED_CREDITS { get; set; }
        public decimal TOTAL_CREDITS { get; set; }
        public decimal TRANSFER_CREDITS { get; set; }
        public decimal GPA_CREDITS { get; set; }
        public decimal QUALITY_POINTS { get; set; }
        public decimal GPA { get; set; }
        public int CLASS_RANK { get; set; }
        public int CLASS_SIZE { get; set; }
        public int NUMBER_REPEATS { get; set; }
        public decimal CONTACT_HOURS { get; set; }
        public string SUPPORTING_DETAIL { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public string CL_LEVEL_FOR_RANK { get; set; }
        public string PROGRAM_FOR_RANK { get; set; }
    }
}
