//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSCRIPTDETAIL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSCRIPTDETAIL()
        {
            this.AlternateGrades = new HashSet<AlternateGrade>();
            this.TemporaryAlternateGrades = new HashSet<TemporaryAlternateGrade>();
        }
    
        public string PEOPLE_CODE { get; set; }
        public string PEOPLE_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string EVENT_ID { get; set; }
        public string EVENT_SUB_TYPE { get; set; }
        public string SECTION { get; set; }
        public string TRANSCRIPT_SEQ { get; set; }
        public string ORG_CODE_ID { get; set; }
        public string WEEK_NUMBER { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string EVENT_MED_NAME { get; set; }
        public string EVENT_LONG_NAME { get; set; }
        public string EVENT_TYPE { get; set; }
        public string CIP_CODE { get; set; }
        public string SPEEDE_CODE { get; set; }
        public string SERIAL_ID { get; set; }
        public string CREDIT_TYPE { get; set; }
        public decimal CREDIT { get; set; }
        public decimal CEU { get; set; }
        public decimal MINUTES_WEEK { get; set; }
        public decimal CONTACT_HOURS { get; set; }
        public decimal CREDIT_GRADE { get; set; }
        public decimal CREDIT_BILLING { get; set; }
        public decimal CREDIT_FTE { get; set; }
        public decimal CREDIT_WORKLOAD { get; set; }
        public decimal CREDIT_FED_FA { get; set; }
        public decimal CREDIT_ST_FA { get; set; }
        public decimal CREDIT_CNTY_FA { get; set; }
        public decimal CREDIT_FED_RPT { get; set; }
        public decimal CREDIT_ST_RPT { get; set; }
        public decimal CREDIT_CNTY_RPT { get; set; }
        public string MID_GRADE { get; set; }
        public string FINAL_GRADE { get; set; }
        public decimal FINAL_QUALITY_PNTS { get; set; }
        public string REPEATED { get; set; }
        public string REPEATED_YEAR { get; set; }
        public string REPEATED_TERM { get; set; }
        public string REPEATED_SESSION { get; set; }
        public string REPEATED_ID { get; set; }
        public string REPEATED_SUB_TYPE { get; set; }
        public string REPEATED_SECTION { get; set; }
        public string COURSE_PRINT_RC { get; set; }
        public string COURSE_PRINT_TRAN { get; set; }
        public string ADD_DROP_WAIT { get; set; }
        public System.DateTime STATUS_DATE { get; set; }
        public string PREREG_REG_STATUS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public string ABT_JOIN { get; set; }
        public decimal CLASS_LEVEL_CREDITS { get; set; }
        public decimal CONTACT_HR_SESSION { get; set; }
        public string HONORS { get; set; }
        public string REFERENCE_EVENT_ID { get; set; }
        public string REFERENCE_SUB_TYPE { get; set; }
        public string ATTEND_STATUS { get; set; }
        public Nullable<System.DateTime> LAST_ATTEND_DATE { get; set; }
        public string COMMENT_EXIST { get; set; }
        public string SPONSOR_CODE_ID { get; set; }
        public Nullable<int> AGREEMENT_NUMBER { get; set; }
        public string REFERENCE_NUMBER_1 { get; set; }
        public string REFERENCE_NUMBER_2 { get; set; }
        public Nullable<System.DateTime> STATUS_TIME { get; set; }
        public string PROTECT_AGREEMENT_FLAG { get; set; }
        public string MILITARY_REFERENCE_CODE { get; set; }
        public int TranscriptDetailId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlternateGrade> AlternateGrades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TemporaryAlternateGrade> TemporaryAlternateGrades { get; set; }
    }
}
