//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSCRIPTGRADING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSCRIPTGRADING()
        {
            this.TranscriptGradingHistories = new HashSet<TranscriptGradingHistory>();
        }
    
        public int RECORD_NUMBER { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string EVENT_ID { get; set; }
        public string EVENT_SUB_TYPE { get; set; }
        public string SECTION { get; set; }
        public int SECTIONGRADING_KEY { get; set; }
        public string GRADE_ACTIVITY { get; set; }
        public Nullable<System.DateTime> ASSIGNMENT_DATE { get; set; }
        public Nullable<System.DateTime> DUE_DATE { get; set; }
        public Nullable<System.DateTime> COMPLETION_DATE { get; set; }
        public string PSEUDO_ID { get; set; }
        public string EXAM_RECEIVED { get; set; }
        public string STUDENT_GRADE { get; set; }
        public Nullable<decimal> GRADE_POINTS { get; set; }
        public decimal PERCENTAGE_FINAL { get; set; }
        public decimal PERCENTAGE_MID { get; set; }
        public string INSTRUCTOR_COMMENTS { get; set; }
        public string STUDENT_COMMENTS { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public int StudentId { get; set; }
        public Nullable<System.DateTime> SubmittedMediaDate { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranscriptGradingHistory> TranscriptGradingHistories { get; set; }
    }
}
