//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRANSACTION()
        {
            this.TRANSACTIONLOGs = new HashSet<TRANSACTIONLOG>();
        }
    
        public long TRANSACTION_ID { get; set; }
        public string SOURCE { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string STATE { get; set; }
        public int FAILED_SEQUENCE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
        public System.DateTime StartDatetime { get; set; }
        public System.DateTime ExpirationDatetime { get; set; }
        public Nullable<int> PaymentTransactionId { get; set; }
    
        public virtual PaymentTransaction PaymentTransaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRANSACTIONLOG> TRANSACTIONLOGs { get; set; }
    }
}
