//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TranscriptGradingHistory
    {
        public int TranscriptGradingHistoryId { get; set; }
        public int RecordNumber { get; set; }
        public int StudentId { get; set; }
        public int SectionId { get; set; }
        public int AssignmentTypeId { get; set; }
        public string PreviousGrade { get; set; }
        public Nullable<decimal> PreviousGradePoints { get; set; }
        public string NewGrade { get; set; }
        public Nullable<decimal> NewGradePoints { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ModifiedById { get; set; }
        public string ModifiedByOpid { get; set; }
        public Nullable<System.DateTime> CreateDatetime { get; set; }
    
        public virtual ABT_USERS ABT_USERS { get; set; }
        public virtual TRANSCRIPTGRADING TRANSCRIPTGRADING { get; set; }
    }
}
