//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSCRIPTSOURCEDISCOUNT
    {
        public int DISCOUNT_ORDER { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string ACADEMIC_YEAR { get; set; }
        public string ACADEMIC_TERM { get; set; }
        public string ACADEMIC_SESSION { get; set; }
        public string EVENT_ID { get; set; }
        public string EVENT_SUB_TYPE { get; set; }
        public string SECTION { get; set; }
        public string SOURCE_ID { get; set; }
        public string DISCOUNT_CODE { get; set; }
        public string CHARGE_CREDIT_CODE { get; set; }
        public string PERCT_FLAT { get; set; }
        public decimal DISCOUNT_AMOUNT { get; set; }
        public decimal DISCOUNT_PERCENTAGE { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
