//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction1
    {
        public int TransactionId { get; set; }
        public System.Guid Guid { get; set; }
        public string UserName { get; set; }
        public byte ProcessType { get; set; }
        public byte Action { get; set; }
        public string Language { get; set; }
        public System.DateTime CreateDatetime { get; set; }
    
        public virtual ABT_USERS ABT_USERS { get; set; }
    }
}
