//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSACTIONLOG
    {
        public long TRANSACTION_ID { get; set; }
        public int SEQUENCE { get; set; }
        public string TABLE_NAME { get; set; }
        public string UNDO_PROC { get; set; }
        public int INTEGER_DATA { get; set; }
        public string VALUE_01 { get; set; }
        public string VALUE_02 { get; set; }
        public string VALUE_03 { get; set; }
        public string VALUE_04 { get; set; }
        public string VALUE_05 { get; set; }
        public string VALUE_06 { get; set; }
        public string VALUE_07 { get; set; }
        public string VALUE_08 { get; set; }
        public string VALUE_09 { get; set; }
        public string VALUE_10 { get; set; }
        public string VALUE_11 { get; set; }
        public string VALUE_12 { get; set; }
        public string VALUE_13 { get; set; }
        public string VALUE_14 { get; set; }
        public string VALUE_15 { get; set; }
        public string VALUE_16 { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    
        public virtual TRANSACTION TRANSACTION { get; set; }
    }
}
