//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UIArea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UIArea()
        {
            this.SessionPeriodFilters = new HashSet<SessionPeriodFilter>();
        }
    
        public byte UIAreaId { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UISubAreaId { get; set; }
        public bool IsActive { get; set; }
        public int Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionPeriodFilter> SessionPeriodFilters { get; set; }
    }
}
