//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOADLAYOUTCOLUMN
    {
        public int UPLOADCOLUMN_ID { get; set; }
        public string FILE_TYPE { get; set; }
        public string UPLOAD_TYPE { get; set; }
        public string FORMAT { get; set; }
        public int UP_COLUMN { get; set; }
        public int UP_COLUMN_POS { get; set; }
        public int UP_COLUMN_LEN { get; set; }
        public string PC_TABLE { get; set; }
        public string PC_COLUMN { get; set; }
        public int RECORD_NUMBER { get; set; }
        public string PC_DEFAULT { get; set; }
        public string UPPER_LOWER_CON { get; set; }
        public string DATE_QUALIFIER { get; set; }
        public string DATE_FORMAT { get; set; }
    }
}
