//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOADLAYOUTMAP
    {
        public int UPLOADMAPPING_ID { get; set; }
        public string FILE_TYPE { get; set; }
        public string UPLOAD_TYPE { get; set; }
        public string FORMAT { get; set; }
        public string PC_TABLE { get; set; }
        public string PC_COLUMN { get; set; }
        public string PC_VALUE { get; set; }
        public string FILE_VALUE { get; set; }
    }
}
