//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPLOADLAYOUTHEADER
    {
        public int UPLOAD_ID { get; set; }
        public string FILE_TYPE { get; set; }
        public string UPLOAD_TYPE { get; set; }
        public string FORMAT { get; set; }
        public string FIXED_VARIABLE { get; set; }
        public string HEADER_ROW { get; set; }
        public string DELIMITER { get; set; }
        public string TEXT_QUALIFIER { get; set; }
        public string DATE_QUALIFIER { get; set; }
        public string DATE_FORMAT { get; set; }
        public string DATE_YEAR { get; set; }
        public string PATH_NAME { get; set; }
        public string TEXT_FILE_NAME { get; set; }
        public string SOURCE_EXISTING { get; set; }
        public string SOURCE_NEW { get; set; }
        public string ACTION_EXISTING { get; set; }
        public string ACTION_NEW { get; set; }
        public string NEW_NAMES { get; set; }
        public string ALLOW_OVERWRITE { get; set; }
    }
}
