//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UPR00100
    {
        public string EMPLOYID { get; set; }
        public string EMPLCLAS { get; set; }
        public byte INACTIVE { get; set; }
        public string LASTNAME { get; set; }
        public string FRSTNAME { get; set; }
        public string MIDLNAME { get; set; }
        public string ADRSCODE { get; set; }
        public string SOCSCNUM { get; set; }
        public System.DateTime BRTHDATE { get; set; }
        public short GENDER { get; set; }
        public short ETHNORGN { get; set; }
        public byte CALC_MIN_WAGE_BAL { get; set; }
        public string DIVISIONCODE_I { get; set; }
        public string DEPRTMNT { get; set; }
        public string JOBTITLE { get; set; }
        public string SUPERVISORCODE_I { get; set; }
        public string LOCATNID { get; set; }
        public short WCACFPAY { get; set; }
        public int ACTINDX { get; set; }
        public short WKHRPRYR { get; set; }
        public System.DateTime STRTDATE { get; set; }
        public System.DateTime DEMPINAC { get; set; }
        public string RSNEMPIN { get; set; }
        public decimal MINETPAY { get; set; }
        public string SUTASTAT { get; set; }
        public string WRKRCOMP { get; set; }
        public byte ATACRVAC { get; set; }
        public int VACCRAMT { get; set; }
        public short VACCRMTH { get; set; }
        public int VACAPRYR { get; set; }
        public int VACAVLBL { get; set; }
        public byte WRNVCNFLSBLWZR { get; set; }
        public byte ATACRSTM { get; set; }
        public short STMACMTH { get; set; }
        public int SKTMACAM { get; set; }
        public int SIKTIMAV { get; set; }
        public int SKTMHPYR { get; set; }
        public byte WRNSTFLSBLWZR { get; set; }
        public string USERDEF1 { get; set; }
        public string USERDEF2 { get; set; }
        public short EMPLOYMENTTYPE { get; set; }
        public short MARITALSTATUS { get; set; }
        public System.DateTime BENADJDATE { get; set; }
        public System.DateTime LASTDAYWORKED_I { get; set; }
        public short BIRTHDAY { get; set; }
        public short BIRTHMONTH { get; set; }
        public string SPOUSE { get; set; }
        public string SPOUSESSN { get; set; }
        public string NICKNAME { get; set; }
        public string ALTERNATENAME { get; set; }
        public short HRSTATUS { get; set; }
        public System.DateTime DATEOFLASTREVIEW_I { get; set; }
        public System.DateTime DATEOFNEXTREVIEW_I { get; set; }
        public System.DateTime BENEFITEXPIRE_I { get; set; }
        public byte HANDICAPPED { get; set; }
        public byte VETERAN { get; set; }
        public byte VIETNAMVETERAN { get; set; }
        public byte DISABLEDVETERAN { get; set; }
        public byte UNIONEMPLOYEE { get; set; }
        public byte SMOKER_I { get; set; }
        public byte CITIZEN { get; set; }
        public byte VERIFIED { get; set; }
        public System.DateTime I9RENEW { get; set; }
        public string PRIMARY_PAY_RECORD { get; set; }
        public string CHANGEBY_I { get; set; }
        public System.DateTime CHANGEDATE_I { get; set; }
        public decimal NOTEINDX { get; set; }
        public decimal NOTEINDX2 { get; set; }
        public string UNIONCD { get; set; }
        public string RATECLSS { get; set; }
        public string FEDCLSSCD { get; set; }
        public byte OTHERVET { get; set; }
        public int DEX_ROW_ID { get; set; }
    }
}
