//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccountProvision
    {
        public int UserAccountProvisionId { get; set; }
        public string UserStoreNameAuth { get; set; }
        public string UserStoreNameCreation { get; set; }
        public string AccountFormatJson { get; set; }
        public string AccountFormatJsonDefault { get; set; }
        public Nullable<byte> Area { get; set; }
        public int RoleId { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public Nullable<int> CreatePersonId { get; set; }
        public System.DateTime RevisionDatetime { get; set; }
        public Nullable<int> RevisionPersonId { get; set; }
    
        public virtual SiteMapRole SiteMapRole { get; set; }
    }
}
