//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEBAUTHORIZEPERCEPTION
    {
        public int AUTHORIZATION_ID { get; set; }
        public string PEOPLE_CODE_ID { get; set; }
        public string LOGIN_ID { get; set; }
        public string ASSESSMENT_ID { get; set; }
        public string EVENT_ID { get; set; }
        public string SECTION { get; set; }
        public System.DateTime AUTHORIZATION_TIME { get; set; }
        public string ACTIVITY { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public System.DateTime CREATE_TIME { get; set; }
        public string CREATE_OPID { get; set; }
        public string CREATE_TERMINAL { get; set; }
        public System.DateTime REVISION_DATE { get; set; }
        public System.DateTime REVISION_TIME { get; set; }
        public string REVISION_OPID { get; set; }
        public string REVISION_TERMINAL { get; set; }
    }
}
