//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEBLOGINLOCKOUT
    {
        public string PEOPLE_CODE_ID { get; set; }
        public string REQUEST_IP_ADDR { get; set; }
        public int ATTEMPTS { get; set; }
        public System.DateTime FIRST_ATTEMPT_TIME { get; set; }
        public System.DateTime LAST_ATTEMPT_TIME { get; set; }
        public string ACCOUNT_LOCKED { get; set; }
    }
}
