//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class WORKCASHRECEIPTDIST
    {
        public int RECEIPT_NUMBER { get; set; }
        public string GL_ACCOUNT { get; set; }
        public decimal AMOUNT { get; set; }
        public int SEQUENCE { get; set; }
        public int PAY_PLAN_NUMBER { get; set; }
        public int WORK_RECEIPT_NUMBER { get; set; }
    }
}
